import {Schema} from 'effect'

export const CurrencyCode = Schema.Literal(
  'AED',
  'ALL',
  'ANG',
  'AOA',
  'ARS',
  'AUD',
  'AZN',
  'BBD',
  'BDT',
  'BGN',
  'BHD',
  'BIF',
  'BMD',
  'BOB',
  'BRL',
  'BSD',
  // 'BTC',
  'BWP',
  'BYN',
  'BZD',
  'CAD',
  'CDF',
  'CHF',
  'CLP',
  'CNY',
  'COP',
  'CRC',
  'CUP',
  'CZK',
  'DJF',
  'DKK',
  'DOP',
  'DZD',
  'EGP',
  'ETB',
  'EUR',
  'FJD',
  'GBP',
  'GEL',
  'GHS',
  'GNF',
  'GTQ',
  'HKD',
  'HNL',
  'HTG',
  'HUF',
  'IDR',
  'ILS',
  'INR',
  'IRR',
  'IRT',
  'ISK',
  'JMD',
  'JOD',
  'JPY',
  'KES',
  'KGS',
  'KHR',
  'KRW',
  'KWD',
  'KZT',
  'LAK',
  'LBP',
  'LKR',
  'LRD',
  'LSL',
  'MAD',
  'MDL',
  'MGA',
  'MKD',
  'MMK',
  'MNT',
  'MOP',
  'MRU',
  'MUR',
  'MVR',
  'MWK',
  'MXN',
  'MYR',
  'MZN',
  'NAD',
  'NGN',
  'NIO',
  'NOK',
  'NPR',
  'NZD',
  'OMR',
  'PAB',
  'PEN',
  'PGK',
  'PHP',
  'PKR',
  'PLN',
  'PYG',
  'QAR',
  'RON',
  'RSD',
  'RUB',
  'RWF',
  'SAR',
  'SCR',
  'SEK',
  'SGD',
  'SLL',
  'SOS',
  'SRD',
  'SZL',
  'THB',
  'TJS',
  'TMT',
  'TND',
  'TOP',
  'TRY',
  'TTD',
  'TWD',
  'TZS',
  'UAH',
  'UGX',
  'USD',
  'UYU',
  'UZS',
  'VES',
  'VND',
  'VUV',
  'WST',
  'XAF',
  'XAG',
  'XAU',
  'XCD',
  // 'XDR',
  'XOF',
  // 'XPD',
  'XPF',
  // 'XPT',
  'ZAR',
  'ZMW',
  'ZWL'
)
export type CurrencyCode = typeof CurrencyCode.Type

export const CurrencyFlag = Schema.String.pipe(Schema.brand('CurrencyFlag'))
export type CurrencyFlag = typeof CurrencyFlag.Type

export const CurrencyName = Schema.String.pipe(Schema.brand('CurrencyName'))
export type CurrencyName = typeof CurrencyName.Type

export const CurrencySymbol = Schema.String.pipe(Schema.brand('CurrencySymbol'))
export type CurrencySymbol = typeof CurrencySymbol.Type

export const CurrencyInfo = Schema.Struct({
  code: CurrencyCode,
  flag: CurrencyFlag,
  name: CurrencyName,
  symbol: CurrencySymbol,
  maxAmount: Schema.Number,
  position: Schema.Literal('before', 'after'),
  countryCode: Schema.Array(Schema.Number),
})
export type CurrencyInfo = typeof CurrencyInfo.Type

// export const ListOfCurrencies = {
//   'AED': 'United Arab Emirates Dirham',
//   'ALL': 'Albanian Lek',
//   'ANG': 'Netherlands Antillean Guilder',
//   'AOA': 'Angolan Kwanza',
//   'ARS': 'Argentine Peso',
//   'AUD': 'Australian Dollar',
//   'AZN': 'Azerbaijani Manat',
//   'BDT': 'Bangladeshi Taka',
//   'BGN': 'Bulgarian Lev',
//   'BHD': 'Bahraini Dinar',
//   'BIF': 'Burundian Franc',
//   'BMD': 'Bermudan Dollar',
//   'BOB': 'Bolivian Boliviano',
//   'BRL': 'Brazilian Real',
//   'BTC': 'Bitcoin',
//   'BWP': 'Botswanan Pula',
//   'BYN': 'Belarusian Ruble',
//   'BZD': 'Belize Dollar',
//   'CAD': 'Canadian Dollar',
//   'CDF': 'Congolese Franc',
//   'CHF': 'Swiss Franc',
//   'CLP': 'Chilean Peso',
//   'CNY': 'Chinese Yuan',
//   'COP': 'Colombian Peso',
//   'CRC': 'Costa Rican Colón',
//   'CUP': 'Cuban Peso',
//   'CZK': 'Czech Republic Koruna',
//   'DJF': 'Djiboutian Franc',
//   'DKK': 'Danish Krone',
//   'DOP': 'Dominican Peso',
//   'DZD': 'Algerian Dinar',
//   'EGP': 'Egyptian Pound',
//   'ETB': 'Ethiopian Birr',
//   'EUR': 'Euro',
//   'GBP': 'British Pound Sterling',
//   'GEL': 'Georgian Lari',
//   'GHS': 'Ghanaian Cedi',
//   'GNF': 'Guinean Franc',
//   'GTQ': 'Guatemalan Quetzal',
//   'HKD': 'Hong Kong Dollar',
//   'HNL': 'Honduran Lempira',
//   'HUF': 'Hungarian Forint',
//   'IDR': 'Indonesian Rupiah',
//   'ILS': 'Israeli New Sheqel',
//   'INR': 'Indian Rupee',
//   'IRR': 'Iranian Rial',
//   'IRT': 'Iranian Toman',
//   'ISK': 'Icelandic Króna',
//   'JMD': 'Jamaican Dollar',
//   'JOD': 'Jordanian Dinar',
//   'JPY': 'Japanese Yen',
//   'KES': 'Kenyan Shilling',
//   'KGS': 'Kyrgystani Som',
//   'KRW': 'South Korean Won',
//   'KZT': 'Kazakhstani Tenge',
//   'LBP': 'Lebanese Pound',
//   'LKR': 'Sri Lankan Rupee',
//   'MAD': 'Moroccan Dirham',
//   'MGA': 'Malagasy Ariary',
//   'MLC': 'Cuban MLC',
//   'MRU': 'Mauritanian Ouguiya',
//   'MXN': 'Mexican Peso',
//   'MYR': 'Malaysian Ringgit',
//   'NAD': 'Namibian Dollar',
//   'NGN': 'Nigerian Naira',
//   'NIO': 'Nicaraguan Córdoba',
//   'NOK': 'Norwegian Krone',
//   'NPR': 'Nepalese Rupee',
//   'NZD': 'New Zealand Dollar',
//   'PAB': 'Panamanian Balboa',
//   'PEN': 'Peruvian Nuevo Sol',
//   'PHP': 'Philippine Peso',
//   'PKR': 'Pakistani Rupee',
//   'PLN': 'Polish Zloty',
//   'PYG': 'Paraguayan Guarani',
//   'QAR': 'Qatari Rial',
//   'RON': 'Romanian Leu',
//   'RSD': 'Serbian Dinar',
//   'RUB': 'Russian Ruble',
//   'RWF': 'Rwandan Franc',
//   'SAR': 'Saudi Riyal',
//   'SEK': 'Swedish Krona',
//   'SGD': 'Singapore Dollar',
//   'THB': 'Thai Baht',
//   'TND': 'Tunisian Dinar',
//   'TRY': 'Turkish Lira',
//   'TTD': 'Trinidad and Tobago Dollar',
//   'TWD': 'New Taiwan Dollar',
//   'TZS': 'Tanzanian Shilling',
//   'UAH': 'Ukrainian Hryvnia',
//   'UGX': 'Ugandan Shilling',
//   'USD': 'United States Dollar',
//   'UYU': 'Uruguayan Peso',
//   'UZS': 'Uzbekistan Som',
//   'VES': 'Venezuelan Bolívar Soberano',
//   'VND': 'Vietnamese Dong',
//   'XAF': 'CFA Franc BEAC',
//   'XAG': 'Silver Ounce',
//   'XAU': 'Gold Ounce',
//   'XOF': 'CFA Franc BCEAO',
//   'XPT': 'Platinum Ounce',
//   'ZAR': 'South African Rand',
// } as const
