base_path: "packages/localization"
base_url: "https://api.crowdin.com"
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: 1
files:
  - source: "**/**.json"
    ignore:
      - package.json
      - .gitignore
      - tsconfig.json
      - "*-*.json"
    translation: /%two_letters_code%-%original_file_name%
