base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /packages/localization-next
    ignore:
      - package.json
    translation: /%two_letters_code%-%original_file_name%
