base_path: /packages/localization-next
base_url: "https://api.crowdin.com"
preserve_hierarchy: 1
files:
  - source: /
    ignore:
      - package.json
      - .gitignore
      - "*-*.json"
    translation: /%original_file_name%-%two_letters_code%
