base_path: /packages/localization-next
base_url: "https://api.crowdin.com"
preserve_hierarchy: 1
files:
  - source: /
    ignore:
      - package.json
    translation: /%two_letters_code%-%original_file_name%
