export const HEADER_PUBLIC_KEY = 'public-key'
export const HEADER_HASH = 'hash'
export const HEADER_SIGNATURE = 'signature'
export const HEADER_CRYPTO_VERSION = 'crypto-version'
export const HEADER_PLATFORM = 'X-Platform'
export const HEADER_CLIENT_VERSION = 'client-version'
