import {Schema} from 'effect'
import sodium from 'libsodium-wrappers'

/**
 * Upper bound for a single random value generated by this module. Migration
 * only needs short random values (transfer ids, pairing capabilities, nonces,
 * staging keys), so anything larger is a programming error.
 */
export const MAX_RANDOM_BYTES = 1024

/**
 * Error thrown when an invalid byte length is requested.
 */
export class RandomBytesError extends Schema.TaggedError<RandomBytesError>(
  'RandomBytesError'
)('RandomBytesError', {
  message: Schema.String,
}) {}

function validateByteLength(byteLength: number): void {
  if (
    !Number.isSafeInteger(byteLength) ||
    byteLength <= 0 ||
    byteLength > MAX_RANDOM_BYTES
  ) {
    throw new RandomBytesError({
      message: `Requested random byte length must be an integer between 1 and ${MAX_RANDOM_BYTES}`,
    })
  }
}

/**
 * Generates cryptographically secure random bytes using the platform CSPRNG
 * (sodium.randombytes_buf).
 */
export async function generateRandomBytes(
  byteLength: number
): Promise<Uint8Array> {
  await sodium.ready
  validateByteLength(byteLength)
  return sodium.randombytes_buf(byteLength)
}

/**
 * Generates `byteLength` cryptographically secure random bytes and returns
 * them encoded as unpadded base64url (sodium URLSAFE_NO_PADDING variant).
 *
 * Used for transfer identifiers, one-time pairing capabilities, command
 * nonces, and staging keys.
 */
export async function generateRandomBase64Url(
  byteLength: number
): Promise<string> {
  await sodium.ready
  validateByteLength(byteLength)
  return sodium.to_base64(
    sodium.randombytes_buf(byteLength),
    sodium.base64_variants.URLSAFE_NO_PADDING
  )
}
