import {SqlClient} from '@effect/sql'
import {Effect} from 'effect'

export default Effect.flatMap(
  SqlClient.SqlClient,
  (sql) => sql`
    CREATE TABLE vexl_product_notifications (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_vexl_product_notifications" PRIMARY KEY,
      UUID UUID NOT NULL UNIQUE,
      title varchar NOT NULL,
      description varchar NOT NULL,
      issue_push_notification boolean NOT NULL,
      date timestamptz NOT NULL,
      action_link varchar,
      action_text varchar,
      type varchar NOT NULL,
      created_at timestamptz NOT NULL DEFAULT now()
    );

    CREATE INDEX vexl_product_notifications_uuid_idx ON vexl_product_notifications (UUID);

    CREATE INDEX vexl_product_notifications_date_id_idx ON vexl_product_notifications (date, id);
  `
)
