import {SqlClient} from '@effect/sql'
import {Effect} from 'effect'

export default Effect.flatMap(
  SqlClient.SqlClient,
  (sql) => sql`
    CREATE TABLE "group" (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_Group" PRIMARY KEY,
      UUID varchar(1500) NOT NULL,
      name varchar(1500) NOT NULL,
      logo_url varchar(1500),
      qr_code_url varchar NOT NULL,
      created_at bigint NOT NULL,
      expiration_at bigint NOT NULL,
      closure_at bigint NOT NULL,
      code integer NOT NULL,
      created_by varchar NOT NULL
    );

    CREATE INDEX "086cc4a8540b4d579438_ix" ON "group" (UUID);

    CREATE INDEX "88c6403cdcd7415d9c8c_ix" ON "group" (expiration_at);

    CREATE TABLE push (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_Push" PRIMARY KEY,
      group_uuid varchar NOT NULL,
      firebase_token CHARACTER VARYING[] NOT NULL
    );

    CREATE INDEX a757cbd855c64b2f9934_ix ON push (group_uuid);

    CREATE TABLE user_contact (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_users_contact PRIMARY KEY,
      hash_from varchar NOT NULL,
      hash_to varchar NOT NULL
    );

    CREATE INDEX "7b3205d35731428c8ff0_ix" ON user_contact (hash_from);

    CREATE INDEX "6d6d93381c6f4dc58dc1_ix" ON user_contact (hash_to);

    CREATE TABLE users (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_users PRIMARY KEY,
      public_key varchar NOT NULL,
      hash varchar NOT NULL,
      firebase_token varchar,
      refreshed_at date,
      platform text,
      client_version integer DEFAULT 0 NOT NULL,
      last_new_content_notification_sent_at date
    );

    CREATE INDEX fa8fa5318f0b4b298baa_ix ON users (public_key);

    CREATE INDEX "5834a3584c634d0fab53_ix" ON users (hash);

    CREATE INDEX a90098b876d449c8bb4c_ix ON users (firebase_token);
  `
)
