import {SqlClient} from '@effect/sql'
import {Effect} from 'effect'

export default Effect.flatMap(
  SqlClient.SqlClient,
  (sql) => sql`
    -- club table
    CREATE TABLE club (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_club PRIMARY KEY,
      "uuid" UUID NOT NULL UNIQUE,
      name text NOT NULL,
      description text,
      members_count_limit integer NOT NULL,
      club_image_url text,
      valid_until date NOT NULL
    );

    CREATE INDEX "club_uuid_ix" ON club ("uuid");

    CREATE INDEX "club_valid_until_ix" ON club (valid_until);

    -- club_member table
    CREATE TABLE club_member (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_club_member PRIMARY KEY,
      club_id bigint NOT NULL CONSTRAINT fk_club REFERENCES club (id),
      public_key text NOT NULL,
      notification_token text,
      last_refreshed_at bigint,
      is_moderator boolean NOT NULL
    );

    CREATE INDEX "club_member_club_id_ix" ON club_member (club_id, last_refreshed_at);

    CREATE INDEX "club_member_public_key_ix" ON club_member (club_id, public_key);

    -- club_invitation_link table
    CREATE TABLE club_invitation_link (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_club_invitation_link PRIMARY KEY,
      club_id bigint NOT NULL CONSTRAINT fk_club_invitation_link REFERENCES club (id),
      created_by_member_id bigint CONSTRAINT fk_club_invitation_link_user REFERENCES club_member (id),
      for_admin boolean NOT NULL,
      code text NOT NULL UNIQUE
    );

    CREATE INDEX "club_invitation_link_code_ix" ON club_invitation_link (code);

    CREATE INDEX "club_invitation_link_club_id" ON club_invitation_link (club_id);
  `
)
