import {SqlClient} from '@effect/sql'
import {Effect} from 'effect'

export default Effect.flatMap(
  SqlClient.SqlClient,
  (sql) => sql`
    CREATE TABLE challenge (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_Challenge" PRIMARY KEY,
      challenge varchar NOT NULL UNIQUE,
      public_key varchar NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE NOT NULL,
      valid boolean DEFAULT TRUE NOT NULL
    );

    CREATE INDEX "public_key_ix" ON challenge (public_key);

    CREATE INDEX "created_at_ix" ON challenge (created_at);
  `
)
