import {SqlClient} from '@effect/sql'
import {Effect} from 'effect'

export default Effect.flatMap(
  SqlClient.SqlClient,
  (sql) => sql`
    CREATE TABLE club_offer_reported_by (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_club_offer_reported_by" PRIMARY KEY,
      offer_id varchar(64) NOT NULL,
      user_public_key varchar NOT NULL
    );

    CREATE INDEX club_offer_reported_by_offer_user_ix ON club_offer_reported_by (offer_id, user_public_key);
  `
)
