import {SqlClient} from '@effect/sql'
import {Effect} from 'effect'

export default Effect.flatMap(
  SqlClient.SqlClient,
  (sql) => sql`
    CREATE TABLE club_offer_reported_info (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_club_offer_reported_info" PRIMARY KEY,
      offer_id varchar NOT NULL UNIQUE,
      club_uuid UUID NOT NULL,
      reported_at date NOT NULL DEFAULT now()
    );

    CREATE INDEX club_offer_reported_info_offer_club_ix ON club_offer_reported_info (offer_id, club_uuid);
  `
)
