import {SqlClient} from '@effect/sql'
import {Effect} from 'effect'

export default Effect.flatMap(
  SqlClient.SqlClient,
  (sql) => sql`
    CREATE TABLE club_reported_record (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_club_reported_record" PRIMARY KEY,
      user_public_key varchar NOT NULL,
      reported_at timestamptz NOT NULL DEFAULT now()
    );

    CREATE INDEX "club_reported_record_user_ix" ON club_reported_record (user_public_key);
  `
)
