import {SqlClient} from '@effect/sql'
import {Effect} from 'effect'

export default Effect.flatMap(
  SqlClient.SqlClient,
  (sql) => sql`
    CREATE TABLE club_member_count_change (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_club_member_count_change PRIMARY KEY,
      club_id bigint NOT NULL CONSTRAINT fk_club_member_count_change_club REFERENCES club (id),
      DAY date NOT NULL,
      joined_count integer NOT NULL DEFAULT 0,
      left_count integer NOT NULL DEFAULT 0,
      CONSTRAINT club_member_count_change_club_day_uq UNIQUE (club_id, DAY)
    );
  `
)
