import {Effect, Either, Option} from 'effect'
import {parseDeepLink} from './parseDeepLink'

describe('parseDeepLink', () => {
  describe('load-pr-preview', () => {
    // This link format is the contract with CI — pr-preview.yaml generates
    // these links into PR comments.
    it('decodes a link generated by pr-preview.yaml', () => {
      const result = Effect.runSync(
        parseDeepLink(
          'stagingapp.vexl.it://link/?type=load-pr-preview&channel=pr-123'
        )
      )

      if (result.searchParams.type !== 'load-pr-preview')
        throw new Error(`Unexpected link type: ${result.searchParams.type}`)

      expect(result.searchParams.channel).toEqual('pr-123')
      expect(Option.isNone(result.searchParams.version)).toBe(true)
    })

    it('accepts the main preview channel', () => {
      const result = Effect.runSync(
        parseDeepLink(
          'stagingapp.vexl.it://link/?type=load-pr-preview&channel=main'
        )
      )

      if (result.searchParams.type !== 'load-pr-preview')
        throw new Error(`Unexpected link type: ${result.searchParams.type}`)

      expect(result.searchParams.channel).toEqual('main')
    })

    it.each(['production', 'staging', 'pr-abc', 'pr-', 'pr-1x', 'xpr-1'])(
      'rejects channel %s',
      (channel) => {
        const result = Effect.runSync(
          Effect.either(
            parseDeepLink(
              `stagingapp.vexl.it://link/?type=load-pr-preview&channel=${channel}`
            )
          )
        )

        expect(Either.isLeft(result)).toBe(true)
        if (Either.isLeft(result))
          expect(result.left._tag).toEqual('InvalidDeepLinkError')
      }
    )

    it('fails when the link is meant for a newer app version', () => {
      const result = Effect.runSync(
        Effect.either(
          parseDeepLink(
            'stagingapp.vexl.it://link/?type=load-pr-preview&channel=pr-123&version=999.0.0'
          )
        )
      )

      expect(Either.isLeft(result)).toBe(true)
      if (Either.isLeft(result))
        expect(result.left._tag).toEqual('DeepLinkMeantForNewerVersionError')
    })
  })
})
