import {SqlClient} from '@effect/sql'
import {Effect} from 'effect'

export default Effect.flatMap(
  SqlClient.SqlClient,
  (sql) => sql`
    CREATE TABLE databasechangeloglock (
      id integer NOT NULL PRIMARY KEY,
      locked boolean NOT NULL,
      lockgranted timestamp,
      lockedby varchar(255)
    );

    CREATE TABLE databasechangelog (
      id varchar(255) NOT NULL,
      author varchar(255) NOT NULL,
      filename varchar(255) NOT NULL,
      dateexecuted timestamp NOT NULL,
      orderexecuted integer NOT NULL,
      exectype varchar(10) NOT NULL,
      md5sum varchar(35),
      description varchar(255),
      comments varchar(255),
      tag varchar(255),
      liquibase varchar(20),
      contexts varchar(255),
      labels varchar(255),
      deployment_id varchar(10)
    );

    CREATE TABLE challenge (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_Challenge" PRIMARY KEY,
      challenge varchar NOT NULL UNIQUE,
      public_key varchar NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE NOT NULL,
      valid boolean DEFAULT TRUE NOT NULL
    );

    CREATE INDEX "086cc4a8540b4d579438_ix" ON challenge (public_key);

    CREATE INDEX "88c6403cdcd7415d9c8c_ix" ON challenge (created_at);

    CREATE TABLE inbox (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_Inbox" PRIMARY KEY,
      public_key varchar NOT NULL UNIQUE,
      token varchar,
      platform varchar,
      client_version integer DEFAULT 0 NOT NULL
    );

    CREATE INDEX a757cbd855c64b2f9934_ix ON inbox (public_key);

    CREATE TABLE message (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_Message" PRIMARY KEY,
      inbox_id bigint NOT NULL,
      message varchar NOT NULL,
      sender_public_key varchar NOT NULL,
      pulled boolean DEFAULT FALSE NOT NULL,
      type varchar NOT NULL
    );

    CREATE INDEX "5834a3584c634d0fab53_ix" ON message (sender_public_key);

    CREATE TABLE stats (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_Stats" PRIMARY KEY,
      key varchar NOT NULL,
      value integer NOT NULL,
      date timestamp NOT NULL
    );

    CREATE INDEX de11d18f200d4bc687f1_ix ON stats (key);

    CREATE TABLE white_list (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_WhiteList" PRIMARY KEY,
      inbox_id bigint NOT NULL,
      public_key varchar NOT NULL,
      state varchar NOT NULL,
      date date DEFAULT CURRENT_DATE NOT NULL
    );

    CREATE INDEX fa8fa5318f0b4b298baa_ix ON white_list (public_key);
  `
)
