export const CHAT_NOTIFICATION_TYPE = {
  MESSAGE: 'MESSAGE',
  REQUEST_REVEAL: 'REQUEST_REVEAL',
  APPROVE_REVEAL: 'APPROVE_REVEAL',
  DISAPPROVE_REVEAL: 'DISAPPROVE_REVEAL',
  REQUEST_MESSAGING: 'REQUEST_MESSAGING',
  APPROVE_MESSAGING: 'APPROVE_MESSAGING',
  DISAPPROVE_MESSAGING: 'DISAPPROVE_MESSAGING',
  DELETE_CHAT: 'DELETE_CHAT',
  BLOCK_CHAT: 'BLOCK_CHAT',
  CANCEL_REQUEST_MESSAGING: 'CANCEL_REQUEST_MESSAGING',
} as const

export const CHAT_NOTIFICATION_TYPES = Object.values(CHAT_NOTIFICATION_TYPE)

export const NEW_CONNECTION = 'NEW_APP_USER'
export const INACTIVITY_REMINDER = 'inactivity_reminder'
