import {SqlClient} from '@effect/sql'
import {Effect} from 'effect'

export default Effect.flatMap(
  SqlClient.SqlClient,
  (sql) => sql`
    CREATE TABLE user_verification (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_UserVerification" PRIMARY KEY,
      verification_code varchar,
      phone_number varchar,
      public_key varchar,
      expiration_at TIMESTAMP WITH TIME ZONE,
      challenge varchar,
      phone_verified boolean DEFAULT FALSE,
      user_id bigint,
      verification_sid varchar,
      country_prefix integer
    );

    CREATE INDEX "7b3205d35731428c8ff0_ix" ON user_verification (verification_code);

    CREATE INDEX "6d6d93381c6f4dc58dc1_ix" ON user_verification (public_key);

    CREATE TABLE users (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_Users" PRIMARY KEY,
      public_key varchar NOT NULL UNIQUE,
      country_prefix integer
    );

    CREATE INDEX "88c6403cdcd7415d9c8c_ix" ON users (public_key);
  `
)
