import love from 'eslint-config-love'
import eslintConfigPrettier from 'eslint-config-prettier'

export const baseConfig = [
  {
    ...love,
    files: ['**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx'],
    linterOptions: {
      reportUnusedDisableDirectives: 'warn',
    },
  },
  eslintConfigPrettier,
  {
    rules: {
      // --- Preserved from original standard-with-typescript config ---
      'no-restricted-exports': [
        'error',
        {restrictDefaultExports: {namespaceFrom: true, namedFrom: true}},
      ],
      '@typescript-eslint/no-redeclare': 'off',
      '@typescript-eslint/consistent-type-assertions': 'off',
      '@typescript-eslint/strict-boolean-expressions': 'off',

      // --- Rules new in eslint-config-love (not in standard-with-typescript) ---
      // Disabled to preserve existing codebase behavior during migration
      '@typescript-eslint/no-import-type-side-effects': 'off',
      '@typescript-eslint/no-inferrable-types': 'off',
      '@typescript-eslint/no-magic-numbers': 'off',
      '@typescript-eslint/no-useless-default-assignment': 'off',
      '@typescript-eslint/prefer-destructuring': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-type-assertion': 'off',
      '@typescript-eslint/no-unsafe-enum-comparison': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/require-await': 'off',
      '@typescript-eslint/strict-void-return': 'off',
      '@typescript-eslint/max-params': 'off',
      '@typescript-eslint/init-declarations': 'off',
      '@typescript-eslint/no-base-to-string': 'off',
      '@typescript-eslint/no-duplicate-type-constituents': 'off',
      '@typescript-eslint/no-empty-function': 'off',
      '@typescript-eslint/no-loop-func': 'off',
      '@typescript-eslint/no-misused-spread': 'off',
      '@typescript-eslint/no-redundant-type-constituents': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/no-unnecessary-template-expression': 'off',
      '@typescript-eslint/no-unnecessary-type-arguments': 'off',
      '@typescript-eslint/no-unnecessary-type-conversion': 'off',
      '@typescript-eslint/no-unnecessary-type-parameters': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/non-nullable-type-assertion-style': 'off',
      '@typescript-eslint/prefer-for-of': 'off',
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      '@typescript-eslint/prefer-optional-chain': 'off',
      '@typescript-eslint/switch-exhaustiveness-check': 'off',
      '@typescript-eslint/use-unknown-in-catch-callback-variable': 'off',
      '@typescript-eslint/ban-types': 'off',
      '@eslint-community/eslint-comments/require-description': 'off',
      '@eslint-community/eslint-comments/no-unlimited-disable': 'off',
      'import/enforce-node-protocol-usage': 'off',
      'arrow-body-style': 'off',
      'require-unicode-regexp': 'off',
      complexity: 'off',
      'max-lines': 'off',
      'max-nested-callbacks': 'off',
      eqeqeq: 'off',
      'no-alert': 'off',
      'no-await-in-loop': 'off',
      'no-console': 'off',
      'no-constant-binary-expression': 'off',
      'no-lonely-if': 'off',
      'no-negated-condition': 'off',
      'no-plusplus': 'off',
      'no-promise-executor-return': 'off',
      'no-useless-assignment': 'off',
      'prefer-named-capture-group': 'off',
      'prefer-template': 'off',
      'promise/avoid-new': 'off',
      'require-yield': 'off',
      'no-param-reassign': 'off',
      'operator-assignment': 'off',
      radix: 'off',
      '@typescript-eslint/prefer-string-starts-ends-with': 'off',
      '@typescript-eslint/prefer-regexp-exec': 'off',
      '@typescript-eslint/class-methods-use-this': 'off',
      '@typescript-eslint/unbound-method': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
      'preserve-caught-error': 'off',
    },
  },
  {
    ignores: [
      '**/*.config.js',
      '**/*.config.cjs',
      '**/*.config.mjs',
      '.next',
      'dist/*',
      'pnpm-lock.yaml',
    ],
  },
]

export default baseConfig
