import {
  CurrencyInfo,
  type CurrencyCode,
} from '@vexl-next/domain/src/general/currency.brand'
import {Schema} from 'effect'
import {bigNumberToString} from '../bigNumberToString'

const decodeCurrencyInfo = Schema.decodeSync(CurrencyInfo)

export const MAX_AMOUNT_EUR = 10000

function floorToSigDigits(raw: number, sigDigits = 3): number {
  if (raw <= 0) return 0
  const step = 10 ** (Math.floor(Math.log10(raw)) - (sigDigits - 1))
  return Math.floor(raw / step) * step
}

export function computeMaxAmountForCurrency({
  btcPriceInCurrency,
  btcPriceInEur,
}: {
  btcPriceInCurrency: number | undefined
  btcPriceInEur: number | undefined
}): number {
  if (!btcPriceInCurrency || !btcPriceInEur) return MAX_AMOUNT_EUR
  return floorToSigDigits(MAX_AMOUNT_EUR * (btcPriceInCurrency / btcPriceInEur))
}

export const currencies = {
  'AED': decodeCurrencyInfo({
    code: 'AED',
    flag: '🇦🇪',
    name: 'United Arab Emirates Dirham',
    symbol: 'د.إ',
    position: 'after',
    countryCode: [971],
  }),
  'ALL': decodeCurrencyInfo({
    code: 'ALL',
    flag: '🇦🇱',
    name: 'Albanian Lek',
    symbol: 'L',
    position: 'after',
    countryCode: [355],
  }),
  'ANG': decodeCurrencyInfo({
    code: 'ANG',
    flag: '🇨🇼',
    name: 'Netherlands Antillean Guilder',
    symbol: 'ƒ',
    position: 'after',
    countryCode: [599],
  }),
  'AOA': decodeCurrencyInfo({
    code: 'AOA',
    flag: '🇦🇴',
    name: 'Angolan Kwanza',
    symbol: 'Kz',
    position: 'after',
    countryCode: [244],
  }),
  'ARS': decodeCurrencyInfo({
    code: 'ARS',
    flag: '🇦🇷',
    name: 'Argentine Peso',
    symbol: '$',
    position: 'before',
    countryCode: [54],
  }),
  'AUD': decodeCurrencyInfo({
    code: 'AUD',
    flag: '🇦🇺',
    name: 'Australian Dollar',
    symbol: '$',
    position: 'before',
    countryCode: [61],
  }),
  'AZN': decodeCurrencyInfo({
    code: 'AZN',
    flag: '🇦🇿',
    name: 'Azerbaijani Manat',
    symbol: '₼',
    position: 'after',
    countryCode: [994],
  }),
  'BBD': decodeCurrencyInfo({
    code: 'BBD',
    flag: '🇧🇧',
    name: 'Barbadian Dollar',
    symbol: '$',
    position: 'before',
    countryCode: [1],
  }),
  'BDT': decodeCurrencyInfo({
    code: 'BDT',
    flag: '🇧🇩',
    name: 'Bangladeshi Taka',
    symbol: '৳',
    position: 'after',
    countryCode: [880],
  }),
  'BGN': decodeCurrencyInfo({
    code: 'BGN',
    flag: '🇧🇬',
    name: 'Bulgarian Lev',
    symbol: 'лв',
    position: 'after',
    countryCode: [359],
  }),
  'BHD': decodeCurrencyInfo({
    code: 'BHD',
    flag: '🇧🇭',
    name: 'Bahraini Dinar',
    symbol: 'ب.د',
    position: 'after',
    countryCode: [973],
  }),
  'BIF': decodeCurrencyInfo({
    code: 'BIF',
    flag: '🇧🇮',
    name: 'Burundian Franc',
    symbol: 'FBu',
    position: 'after',
    countryCode: [257],
  }),
  'BMD': decodeCurrencyInfo({
    code: 'BMD',
    flag: '🇧🇲',
    name: 'Bermudian Dollar',
    symbol: '$',
    position: 'before',
    countryCode: [1],
  }),
  'BOB': decodeCurrencyInfo({
    code: 'BOB',
    flag: '🇧🇴',
    name: 'Bolivian Boliviano',
    symbol: 'Bs.',
    position: 'after',
    countryCode: [591],
  }),
  'BRL': decodeCurrencyInfo({
    code: 'BRL',
    flag: '🇧🇷',
    name: 'Brazilian Real',
    symbol: 'R$',
    position: 'before',
    countryCode: [55],
  }),
  'BSD': decodeCurrencyInfo({
    code: 'BSD',
    flag: '🇧🇸',
    name: 'Bahamian Dollar',
    symbol: '$',
    position: 'before',
    countryCode: [1],
  }),
  'BWP': decodeCurrencyInfo({
    code: 'BWP',
    flag: '🇧🇼',
    name: 'Botswana Pula',
    symbol: 'P',
    position: 'after',
    countryCode: [267],
  }),
  'BYN': decodeCurrencyInfo({
    code: 'BYN',
    flag: '🇧🇾',
    name: 'Belarusian Ruble',
    symbol: 'Br',
    position: 'after',
    countryCode: [375],
  }),
  'BZD': decodeCurrencyInfo({
    code: 'BZD',
    flag: '🇧🇿',
    name: 'Belize Dollar',
    symbol: '$',
    position: 'before',
    countryCode: [501],
  }),
  'CAD': decodeCurrencyInfo({
    code: 'CAD',
    flag: '🇨🇦',
    name: 'Canadian Dollar',
    symbol: '$',
    position: 'before',
    countryCode: [1],
  }),
  'CDF': decodeCurrencyInfo({
    code: 'CDF',
    flag: '🇨🇩',
    name: 'Congolese Franc',
    symbol: 'FC',
    position: 'after',
    countryCode: [243],
  }),
  'CHF': decodeCurrencyInfo({
    code: 'CHF',
    flag: '🇨🇭',
    name: 'Swiss Franc',
    symbol: 'CHF',
    position: 'before',
    countryCode: [41],
  }),
  'CLP': decodeCurrencyInfo({
    code: 'CLP',
    flag: '🇨🇱',
    name: 'Chilean Peso',
    symbol: '$',
    position: 'before',
    countryCode: [56],
  }),
  'CNY': decodeCurrencyInfo({
    code: 'CNY',
    flag: '🇨🇳',
    name: 'Chinese Yuan',
    symbol: '¥',
    position: 'after',
    countryCode: [86],
  }),
  'COP': decodeCurrencyInfo({
    code: 'COP',
    flag: '🇨🇴',
    name: 'Colombian Peso',
    symbol: '$',
    position: 'before',
    countryCode: [57],
  }),
  'CRC': decodeCurrencyInfo({
    code: 'CRC',
    flag: '🇨🇷',
    name: 'Costa Rican Colón',
    symbol: '₡',
    position: 'before',
    countryCode: [506],
  }),
  'CUP': decodeCurrencyInfo({
    code: 'CUP',
    flag: '🇨🇺',
    name: 'Cuban Peso',
    symbol: '$',
    position: 'before',
    countryCode: [53],
  }),
  'CZK': decodeCurrencyInfo({
    code: 'CZK',
    flag: '🇨🇿',
    name: 'Czech Koruna',
    symbol: 'Kč',
    position: 'after',
    countryCode: [420],
  }),
  'DJF': decodeCurrencyInfo({
    code: 'DJF',
    flag: '🇩🇯',
    name: 'Djiboutian Franc',
    symbol: 'Fdj',
    position: 'after',
    countryCode: [253],
  }),
  'DKK': decodeCurrencyInfo({
    code: 'DKK',
    flag: '🇩🇰',
    name: 'Danish Krone',
    symbol: 'kr',
    position: 'after',
    countryCode: [45],
  }),
  'DOP': decodeCurrencyInfo({
    code: 'DOP',
    flag: '🇩🇴',
    name: 'Dominican Peso',
    symbol: 'RD$',
    position: 'before',
    countryCode: [1],
  }),
  'DZD': decodeCurrencyInfo({
    code: 'DZD',
    flag: '🇩🇿',
    name: 'Algerian Dinar',
    symbol: 'د.ج',
    position: 'after',
    countryCode: [213],
  }),
  'EGP': decodeCurrencyInfo({
    code: 'EGP',
    flag: '🇪🇬',
    name: 'Egyptian Pound',
    symbol: 'E£',
    position: 'before',
    countryCode: [20],
  }),
  'ETB': decodeCurrencyInfo({
    code: 'ETB',
    flag: '🇪🇹',
    name: 'Ethiopian Birr',
    symbol: 'Br',
    position: 'after',
    countryCode: [251],
  }),
  'EUR': decodeCurrencyInfo({
    code: 'EUR',
    flag: '🇪🇺',
    name: 'Euro',
    symbol: '€',
    position: 'before',
    countryCode: [358],
  }),
  'FJD': decodeCurrencyInfo({
    code: 'FJD',
    flag: '🇫🇯',
    name: 'Fijian Dollar',
    symbol: '$',
    position: 'before',
    countryCode: [679],
  }),
  'GBP': decodeCurrencyInfo({
    code: 'GBP',
    flag: '🇬🇧',
    name: 'British Pound Sterling',
    symbol: '£',
    position: 'before',
    countryCode: [44],
  }),
  'GEL': decodeCurrencyInfo({
    code: 'GEL',
    flag: '🇬🇪',
    name: 'Georgian Lari',
    symbol: '₾',
    position: 'after',
    countryCode: [995],
  }),
  'GHS': decodeCurrencyInfo({
    code: 'GHS',
    flag: '🇬🇭',
    name: 'Ghanaian Cedi',
    symbol: '₵',
    position: 'after',
    countryCode: [233],
  }),
  'GNF': decodeCurrencyInfo({
    code: 'GNF',
    flag: '🇬🇳',
    name: 'Guinean Franc',
    symbol: 'FG',
    position: 'after',
    countryCode: [224],
  }),
  'GTQ': decodeCurrencyInfo({
    code: 'GTQ',
    flag: '🇬🇹',
    name: 'Guatemalan Quetzal',
    symbol: 'Q',
    position: 'after',
    countryCode: [502],
  }),
  'HKD': decodeCurrencyInfo({
    code: 'HKD',
    flag: '🇭🇰',
    name: 'Hong Kong Dollar',
    symbol: 'HK$',
    position: 'before',
    countryCode: [852],
  }),
  'HNL': decodeCurrencyInfo({
    code: 'HNL',
    flag: '🇭🇳',
    name: 'Honduran Lempira',
    symbol: 'L',
    position: 'after',
    countryCode: [504],
  }),
  'HTG': decodeCurrencyInfo({
    code: 'HTG',
    flag: '🇭🇹',
    name: 'Haitian Gourde',
    symbol: 'G',
    position: 'after',
    countryCode: [509],
  }),
  'HUF': decodeCurrencyInfo({
    code: 'HUF',
    flag: '🇭🇺',
    name: 'Hungarian Forint',
    symbol: 'Ft',
    position: 'after',
    countryCode: [36],
  }),
  'IDR': decodeCurrencyInfo({
    code: 'IDR',
    flag: '🇮🇩',
    name: 'Indonesian Rupiah',
    symbol: 'Rp',
    position: 'after',
    countryCode: [62],
  }),
  'ILS': decodeCurrencyInfo({
    code: 'ILS',
    flag: '🇮🇱',
    name: 'Israeli New Shekel',
    symbol: '₪',
    position: 'before',
    countryCode: [972],
  }),
  'INR': decodeCurrencyInfo({
    code: 'INR',
    flag: '🇮🇳',
    name: 'Indian Rupee',
    symbol: '₹',
    position: 'before',
    countryCode: [91],
  }),
  'IRR': decodeCurrencyInfo({
    code: 'IRR',
    flag: '🇮🇷',
    name: 'Iranian Rial',
    symbol: '﷼',
    position: 'after',
    countryCode: [98],
  }),
  'IRT': decodeCurrencyInfo({
    code: 'IRT',
    flag: '🇮🇷',
    name: 'Iranian Toman',
    // There isn’t a universally standardized single-character Unicode symbol for “toman”.
    // The currency name is commonly written out in Persian as “تومان”.
    symbol: 'تومان',
    position: 'after',
    countryCode: [98],
  }),
  'ISK': decodeCurrencyInfo({
    code: 'ISK',
    flag: '🇮🇸',
    name: 'Icelandic Króna',
    symbol: 'kr',
    position: 'after',
    countryCode: [354],
  }),
  'JMD': decodeCurrencyInfo({
    code: 'JMD',
    flag: '🇯🇲',
    name: 'Jamaican Dollar',
    symbol: '$',
    position: 'before',
    countryCode: [1],
  }),
  'JOD': decodeCurrencyInfo({
    code: 'JOD',
    flag: '🇯🇴',
    name: 'Jordanian Dinar',
    symbol: 'د.ا',
    position: 'after',
    countryCode: [962],
  }),
  'JPY': decodeCurrencyInfo({
    code: 'JPY',
    flag: '🇯🇵',
    name: 'Japanese Yen',
    symbol: '¥',
    position: 'after',
    countryCode: [81],
  }),
  'KES': decodeCurrencyInfo({
    code: 'KES',
    flag: '🇰🇪',
    name: 'Kenyan Shilling',
    symbol: 'KSh',
    position: 'after',
    countryCode: [254],
  }),
  'KGS': decodeCurrencyInfo({
    code: 'KGS',
    flag: '🇰🇬',
    name: 'Kyrgyzstani Som',
    symbol: 'сом',
    position: 'after',
    countryCode: [996],
  }),
  'KHR': decodeCurrencyInfo({
    code: 'KHR',
    flag: '🇰🇭',
    name: 'Cambodian Riel',
    symbol: '៛',
    position: 'after',
    countryCode: [855],
  }),
  'KRW': decodeCurrencyInfo({
    code: 'KRW',
    flag: '🇰🇷',
    name: 'South Korean Won',
    symbol: '₩',
    position: 'after',
    countryCode: [82],
  }),
  'KWD': decodeCurrencyInfo({
    code: 'KWD',
    flag: '🇰🇼',
    name: 'Kuwaiti Dinar',
    symbol: 'د.ك',
    position: 'after',
    countryCode: [965],
  }),
  'KZT': decodeCurrencyInfo({
    code: 'KZT',
    flag: '🇰🇿',
    name: 'Kazakhstani Tenge',
    symbol: '₸',
    position: 'after',
    countryCode: [7],
  }),
  'LAK': decodeCurrencyInfo({
    code: 'LAK',
    flag: '🇱🇦',
    name: 'Lao Kip',
    symbol: '₭',
    position: 'after',
    countryCode: [856],
  }),
  'LBP': decodeCurrencyInfo({
    code: 'LBP',
    flag: '🇱🇧',
    name: 'Lebanese Pound',
    symbol: 'ل.ل',
    position: 'after',
    countryCode: [961],
  }),
  'LKR': decodeCurrencyInfo({
    code: 'LKR',
    flag: '🇱🇰',
    name: 'Sri Lankan Rupee',
    symbol: 'Rs',
    position: 'after',
    countryCode: [94],
  }),
  'LRD': decodeCurrencyInfo({
    code: 'LRD',
    flag: '🇱🇷',
    name: 'Liberian Dollar',
    symbol: '$',
    position: 'before',
    countryCode: [231],
  }),
  'LSL': decodeCurrencyInfo({
    code: 'LSL',
    flag: '🇱🇸',
    name: 'Lesotho Loti',
    symbol: 'L',
    position: 'after',
    countryCode: [266],
  }),
  'MAD': decodeCurrencyInfo({
    code: 'MAD',
    flag: '🇲🇦',
    name: 'Moroccan Dirham',
    symbol: 'د.م.',
    position: 'after',
    countryCode: [212],
  }),
  'MDL': decodeCurrencyInfo({
    code: 'MDL',
    flag: '🇲🇩',
    name: 'Moldovan Leu',
    symbol: 'MDL',
    position: 'after',
    countryCode: [373],
  }),
  'MGA': decodeCurrencyInfo({
    code: 'MGA',
    flag: '🇲🇬',
    name: 'Malagasy Ariary',
    symbol: 'Ar',
    position: 'after',
    countryCode: [261],
  }),
  'MKD': decodeCurrencyInfo({
    code: 'MKD',
    flag: '🇲🇰',
    name: 'Macedonian Denar',
    symbol: 'ден',
    position: 'after',
    countryCode: [389],
  }),
  'MMK': decodeCurrencyInfo({
    code: 'MMK',
    flag: '🇲🇲',
    name: 'Myanmar Kyat',
    symbol: 'K',
    position: 'after',
    countryCode: [95],
  }),
  'MNT': decodeCurrencyInfo({
    code: 'MNT',
    flag: '🇲🇳',
    name: 'Mongolian Tugrik',
    symbol: '₮',
    position: 'after',
    countryCode: [976],
  }),
  'MOP': decodeCurrencyInfo({
    code: 'MOP',
    flag: '🇲🇴',
    name: 'Macanese Pataca',
    symbol: 'MOP$',
    position: 'after',
    countryCode: [853],
  }),
  'MRU': decodeCurrencyInfo({
    code: 'MRU',
    flag: '🇲🇷',
    name: 'Mauritanian Ouguiya',
    symbol: 'UM',
    position: 'after',
    countryCode: [222],
  }),
  'MUR': decodeCurrencyInfo({
    code: 'MUR',
    flag: '🇲🇺',
    name: 'Mauritian Rupee',
    symbol: '₨',
    position: 'after',
    countryCode: [230],
  }),
  'MVR': decodeCurrencyInfo({
    code: 'MVR',
    flag: '🇲🇻',
    name: 'Maldivian Rufiyaa',
    symbol: 'ރ.',
    position: 'after',
    countryCode: [960],
  }),
  'MWK': decodeCurrencyInfo({
    code: 'MWK',
    flag: '🇲🇼',
    name: 'Malawian Kwacha',
    symbol: 'MK',
    position: 'after',
    countryCode: [265],
  }),
  'MXN': decodeCurrencyInfo({
    code: 'MXN',
    flag: '🇲🇽',
    name: 'Mexican Peso',
    symbol: '$',
    position: 'before',
    countryCode: [52],
  }),
  'MYR': decodeCurrencyInfo({
    code: 'MYR',
    flag: '🇲🇾',
    name: 'Malaysian Ringgit',
    symbol: 'RM',
    position: 'before',
    countryCode: [60],
  }),
  'MZN': decodeCurrencyInfo({
    code: 'MZN',
    flag: '🇲🇿',
    name: 'Mozambican Metical',
    symbol: 'MT',
    position: 'after',
    countryCode: [258],
  }),
  'NAD': decodeCurrencyInfo({
    code: 'NAD',
    flag: '🇳🇦',
    name: 'Namibian Dollar',
    symbol: '$',
    position: 'before',
    countryCode: [264],
  }),
  'NGN': decodeCurrencyInfo({
    code: 'NGN',
    flag: '🇳🇬',
    name: 'Nigerian Naira',
    symbol: '₦',
    position: 'before',
    countryCode: [234],
  }),
  'NIO': decodeCurrencyInfo({
    code: 'NIO',
    flag: '🇳🇮',
    name: 'Nicaraguan Córdoba',
    symbol: 'C$',
    position: 'before',
    countryCode: [505],
  }),
  'NOK': decodeCurrencyInfo({
    code: 'NOK',
    flag: '🇳🇴',
    name: 'Norwegian Krone',
    symbol: 'kr',
    position: 'after',
    countryCode: [47],
  }),
  'NPR': decodeCurrencyInfo({
    code: 'NPR',
    flag: '🇳🇵',
    name: 'Nepalese Rupee',
    symbol: '₨',
    position: 'before',
    countryCode: [977],
  }),
  'NZD': decodeCurrencyInfo({
    code: 'NZD',
    flag: '🇳🇿',
    name: 'New Zealand Dollar',
    symbol: '$',
    position: 'before',
    countryCode: [64],
  }),
  'OMR': decodeCurrencyInfo({
    code: 'OMR',
    flag: '🇴🇲',
    name: 'Omani Rial',
    symbol: 'ر.ع.',
    position: 'after',
    countryCode: [968],
  }),
  'PAB': decodeCurrencyInfo({
    code: 'PAB',
    flag: '🇵🇦',
    name: 'Panamanian Balboa',
    symbol: 'B/.',
    position: 'before',
    countryCode: [507],
  }),
  'PEN': decodeCurrencyInfo({
    code: 'PEN',
    flag: '🇵🇪',
    name: 'Peruvian Sol',
    symbol: 'S/.',
    position: 'before',
    countryCode: [51],
  }),
  'PGK': decodeCurrencyInfo({
    code: 'PGK',
    flag: '🇵🇬',
    name: 'Papua New Guinean Kina',
    symbol: 'K',
    position: 'before',
    countryCode: [675],
  }),
  'PHP': decodeCurrencyInfo({
    code: 'PHP',
    flag: '🇵🇭',
    name: 'Philippine Peso',
    symbol: '₱',
    position: 'before',
    countryCode: [63],
  }),
  'PKR': decodeCurrencyInfo({
    code: 'PKR',
    flag: '🇵🇰',
    name: 'Pakistani Rupee',
    symbol: '₨',
    position: 'before',
    countryCode: [92],
  }),
  'PLN': decodeCurrencyInfo({
    code: 'PLN',
    flag: '🇵🇱',
    name: 'Polish Zloty',
    symbol: 'zł',
    position: 'after',
    countryCode: [48],
  }),
  'PYG': decodeCurrencyInfo({
    code: 'PYG',
    flag: '🇵🇾',
    name: 'Paraguayan Guarani',
    symbol: '₲',
    position: 'after',
    countryCode: [595],
  }),
  'QAR': decodeCurrencyInfo({
    code: 'QAR',
    flag: '🇶🇦',
    name: 'Qatari Riyal',
    symbol: 'ر.ق',
    position: 'after',
    countryCode: [974],
  }),
  'RON': decodeCurrencyInfo({
    code: 'RON',
    flag: '🇷🇴',
    name: 'Romanian Leu',
    symbol: 'lei',
    position: 'after',
    countryCode: [40],
  }),
  'RSD': decodeCurrencyInfo({
    code: 'RSD',
    flag: '🇷🇸',
    name: 'Serbian Dinar',
    symbol: 'дин.',
    position: 'after',
    countryCode: [381],
  }),
  'RUB': decodeCurrencyInfo({
    code: 'RUB',
    flag: '🇷🇺',
    name: 'Russian Ruble',
    symbol: '₽',
    position: 'after',
    countryCode: [7],
  }),
  'RWF': decodeCurrencyInfo({
    code: 'RWF',
    flag: '🇷🇼',
    name: 'Rwandan Franc',
    symbol: 'FRw',
    position: 'after',
    countryCode: [250],
  }),
  'SAR': decodeCurrencyInfo({
    code: 'SAR',
    flag: '🇸🇦',
    name: 'Saudi Riyal',
    symbol: 'ر.س',
    position: 'after',
    countryCode: [966],
  }),
  'SCR': decodeCurrencyInfo({
    code: 'SCR',
    flag: '🇸🇨',
    name: 'Seychellois Rupee',
    symbol: '₨',
    position: 'before',
    countryCode: [248],
  }),
  'SEK': decodeCurrencyInfo({
    code: 'SEK',
    flag: '🇸🇪',
    name: 'Swedish Krona',
    symbol: 'kr',
    position: 'after',
    countryCode: [46],
  }),
  'SGD': decodeCurrencyInfo({
    code: 'SGD',
    flag: '🇸🇬',
    name: 'Singapore Dollar',
    symbol: '$',
    position: 'before',
    countryCode: [65],
  }),
  'SLL': decodeCurrencyInfo({
    code: 'SLL',
    flag: '🇸🇱',
    name: 'Sierra Leonean Leone',
    symbol: 'Le',
    position: 'after',
    countryCode: [232],
  }),
  'SOS': decodeCurrencyInfo({
    code: 'SOS',
    flag: '🇸🇴',
    name: 'Somali Shilling',
    symbol: 'Sh',
    position: 'after',
    countryCode: [252],
  }),
  'SRD': decodeCurrencyInfo({
    code: 'SRD',
    flag: '🇸🇷',
    name: 'Surinamese Dollar',
    symbol: '$',
    position: 'before',
    countryCode: [597],
  }),
  'SZL': decodeCurrencyInfo({
    code: 'SZL',
    flag: '🇸🇿',
    name: 'Swazi Lilangeni',
    symbol: 'E',
    position: 'after',
    countryCode: [268],
  }),
  'THB': decodeCurrencyInfo({
    code: 'THB',
    flag: '🇹🇭',
    name: 'Thai Baht',
    symbol: '฿',
    position: 'before',
    countryCode: [66],
  }),
  'TJS': decodeCurrencyInfo({
    code: 'TJS',
    flag: '🇹🇯',
    name: 'Tajikistani Somoni',
    symbol: 'ЅМ',
    position: 'after',
    countryCode: [992],
  }),
  'TMT': decodeCurrencyInfo({
    code: 'TMT',
    flag: '🇹🇲',
    name: 'Turkmenistan Manat',
    symbol: 'T',
    position: 'after',
    countryCode: [993],
  }),
  'TND': decodeCurrencyInfo({
    code: 'TND',
    flag: '🇹🇳',
    name: 'Tunisian Dinar',
    symbol: 'د.ت',
    position: 'after',
    countryCode: [216],
  }),
  'TOP': decodeCurrencyInfo({
    code: 'TOP',
    flag: '🇹🇴',
    name: 'Tongan Paʻanga',
    symbol: 'T$',
    position: 'before',
    countryCode: [676],
  }),
  'TRY': decodeCurrencyInfo({
    code: 'TRY',
    flag: '🇹🇷',
    name: 'Turkish Lira',
    symbol: '₺',
    position: 'after',
    countryCode: [90],
  }),
  'TTD': decodeCurrencyInfo({
    code: 'TTD',
    flag: '🇹🇹',
    name: 'Trinidad and Tobago Dollar',
    symbol: '$',
    position: 'before',
    countryCode: [1, 868],
  }),
  'TWD': decodeCurrencyInfo({
    code: 'TWD',
    flag: '🇹🇼',
    name: 'New Taiwan Dollar',
    symbol: 'NT$',
    position: 'before',
    countryCode: [886],
  }),
  'TZS': decodeCurrencyInfo({
    code: 'TZS',
    flag: '🇹🇿',
    name: 'Tanzanian Shilling',
    symbol: 'TSh',
    position: 'after',
    countryCode: [255],
  }),
  'UAH': decodeCurrencyInfo({
    code: 'UAH',
    flag: '🇺🇦',
    name: 'Ukrainian Hryvnia',
    symbol: '₴',
    position: 'after',
    countryCode: [380],
  }),
  'UGX': decodeCurrencyInfo({
    code: 'UGX',
    flag: '🇺🇬',
    name: 'Ugandan Shilling',
    symbol: 'USh',
    position: 'after',
    countryCode: [256],
  }),
  'USD': decodeCurrencyInfo({
    code: 'USD',
    flag: '🇺🇸',
    name: 'United States Dollar',
    symbol: '$',
    position: 'before',
    countryCode: [1],
  }),
  'UYU': decodeCurrencyInfo({
    code: 'UYU',
    flag: '🇺🇾',
    name: 'Uruguayan Peso',
    symbol: '$',
    position: 'before',
    countryCode: [598],
  }),
  'UZS': decodeCurrencyInfo({
    code: 'UZS',
    flag: '🇺🇿',
    name: 'Uzbekistani Som',
    symbol: 'soʻm',
    position: 'after',
    countryCode: [998],
  }),
  'VES': decodeCurrencyInfo({
    code: 'VES',
    flag: '🇻🇪',
    name: 'Venezuelan Bolívar',
    symbol: 'Bs.',
    position: 'before',
    countryCode: [58],
  }),
  'VND': decodeCurrencyInfo({
    code: 'VND',
    flag: '🇻🇳',
    name: 'Vietnamese Dong',
    symbol: '₫',
    position: 'after',
    countryCode: [84],
  }),
  'VUV': decodeCurrencyInfo({
    code: 'VUV',
    flag: '🇻🇺',
    name: 'Vanuatu Vatu',
    symbol: 'Vt',
    position: 'after',
    countryCode: [678],
  }),
  'WST': decodeCurrencyInfo({
    code: 'WST',
    flag: '🇼🇸',
    name: 'Samoan Tala',
    symbol: 'T',
    position: 'before',
    countryCode: [685],
  }),
  'XAF': decodeCurrencyInfo({
    code: 'XAF',
    flag: '🌍',
    name: 'Central African CFA Franc',
    symbol: 'FCFA',
    position: 'after',
    countryCode: [237],
  }),
  'XAG': decodeCurrencyInfo({
    code: 'XAG',
    flag: '⚪',
    name: 'Silver (troy ounce)',
    symbol: 'oz t',
    position: 'after',
    countryCode: [],
  }),
  'XAU': decodeCurrencyInfo({
    code: 'XAU',
    flag: '🟡',
    name: 'Gold (troy ounce)',
    symbol: 'oz t',
    position: 'after',
    countryCode: [],
  }),
  'XCD': decodeCurrencyInfo({
    code: 'XCD',
    flag: '🇧🇶',
    name: 'East Caribbean Dollar',
    symbol: '$',
    position: 'before',
    countryCode: [1],
  }),
  'XOF': decodeCurrencyInfo({
    code: 'XOF',
    flag: '🌍',
    name: 'West African CFA Franc',
    symbol: 'CFA',
    position: 'after',
    countryCode: [225],
  }),
  'XPF': decodeCurrencyInfo({
    code: 'XPF',
    flag: '🇵🇫',
    name: 'CFP Franc',
    symbol: '₣',
    position: 'after',
    countryCode: [687],
  }),
  'ZAR': decodeCurrencyInfo({
    code: 'ZAR',
    flag: '🇿🇦',
    name: 'South African Rand',
    symbol: 'R',
    position: 'before',
    countryCode: [27],
  }),
  'ZMW': decodeCurrencyInfo({
    code: 'ZMW',
    flag: '🇿🇲',
    name: 'Zambian Kwacha',
    symbol: 'ZK',
    position: 'after',
    countryCode: [260],
  }),
  'ZWL': decodeCurrencyInfo({
    code: 'ZWL',
    flag: '🇿🇼',
    name: 'Zimbabwean Dollar',
    symbol: '$',
    position: 'before',
    countryCode: [263],
  }),
} as const

export function getCurrencyLeftText(
  code: CurrencyCode | undefined
): string | undefined {
  if (!code) return undefined
  const currency = currencies[code]
  if (currency.position !== 'before') return undefined
  return currency.symbol
}

export function getCurrencyRightText(
  code: CurrencyCode | undefined
): string | undefined {
  if (!code) return undefined
  const currency = currencies[code]
  if (currency.position !== 'after') return undefined
  return currency.symbol
}

export function formatCurrencyAmount(
  code: CurrencyCode,
  amount: number
): string {
  const currency = currencies[code]
  if (currency.position === 'before') {
    return `${currency.symbol}${bigNumberToString(amount)}`
  }
  return `${bigNumberToString(amount)} ${currency.symbol}`
}
