import {SqlClient} from '@effect/sql'
import {Effect} from 'effect'

export default Effect.flatMap(
  SqlClient.SqlClient,
  (sql) => sql`
    CREATE TABLE "metrics" (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_Metrics" PRIMARY KEY,
      UUID UUID NOT NULL UNIQUE,
      name varchar NOT NULL,
      value integer NOT NULL,
      "timestamp" timestamp NOT NULL,
      attributes jsonb,
      type varchar NOT NULL
    );

    CREATE INDEX idx_metrics_name_timestamp ON metrics (name, "timestamp");

    CREATE TABLE "dead_metrics" (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_DeadMetrics" PRIMARY KEY,
      data jsonb NOT NULL,
      message varchar,
      accepted_at timestamp NOT NULL
    );
  `
)
