import {SqlClient} from '@effect/sql'
import {Effect} from 'effect'

export default Effect.flatMap(
  SqlClient.SqlClient,
  (sql) => sql`
    CREATE TABLE last_reported_by_service (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_LastReportedByService" PRIMARY KEY,
      service_name varchar NOT NULL UNIQUE,
      last_event_at TIMESTAMP WITH TIME ZONE
    );
  `
)
