import {SqlClient} from '@effect/sql'
import {Effect} from 'effect'

export default Effect.flatMap(
  SqlClient.SqlClient,
  (sql) => sql`
    CREATE TABLE analytics_states (
      pk bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_AnalyticsStates" PRIMARY KEY,
      id uuid,
      kind varchar NOT NULL,
      name varchar NOT NULL,
      schema_version integer NOT NULL,
      revision integer NOT NULL,
      start_day date NOT NULL,
      updated_day date NOT NULL,
      payload jsonb NOT NULL,
      app_platform varchar NOT NULL,
      app_major_version varchar NOT NULL,
      country_prefix varchar NOT NULL
    );

    CREATE UNIQUE INDEX idx_analytics_states_id ON analytics_states (id)
    WHERE
      id IS NOT NULL;

    CREATE INDEX idx_analytics_states_name_start_day ON analytics_states (name, start_day);
  `
)
