apiVersion: 1

datasources:
  - name: Vexl Local Traces
    uid: vexl-local-traces
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      httpMethod: GET
