import {SqlClient} from '@effect/sql'
import {Effect} from 'effect'

export const createNotificationTokens = Effect.flatMap(
  SqlClient.SqlClient,
  (sql) => sql`
    CREATE TABLE IF NOT EXISTS notification_token_secrets (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_notification_secret PRIMARY KEY,
      secret VARCHAR(255) NOT NULL UNIQUE,
      expo_notification_token VARCHAR(255),
      client_platform VARCHAR(50) NOT NULL,
      client_version INTEGER NOT NULL,
      client_app_source VARCHAR(50) NOT NULL,
      client_language VARCHAR(10) NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMP NOT NULL DEFAULT NOW()
    );

    CREATE INDEX IF NOT EXISTS idx_notification_secrets_secret ON notification_secrets (secret);

    CREATE INDEX IF NOT EXISTS idx_notification_secrets_expo_token ON notification_secrets (expo_notification_token);

    CREATE TABLE IF NOT EXISTS notification_tokens (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_notification_tokens PRIMARY KEY,
      token VARCHAR(255) NOT NULL,
      secret_id BIGINT NOT NULL REFERENCES notification_token_secrets (id) ON DELETE CASCADE,
      UNIQUE (token, secret_id)
    );

    CREATE INDEX IF NOT EXISTS idx_notification_tokens_token ON notification_tokens (token);

    CREATE INDEX IF NOT EXISTS idx_notification_tokens_secret_id ON notification_tokens (secret_id);
  `
)
