import {Effect} from 'effect'
import {SqlClient} from 'effect/unstable/sql'

export const createPendingBatchedNotifications = Effect.flatMap(
  SqlClient.SqlClient,
  (sql) => sql`
    CREATE TABLE IF NOT EXISTS pending_batched_notifications (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      created_at timestamptz NOT NULL DEFAULT now(),
      notification_data jsonb NOT NULL
    );
  `
)
