import {SqlClient} from '@effect/sql'
import {Effect} from 'effect'

export default Effect.flatMap(
  SqlClient.SqlClient,
  (sql) => sql`
    CREATE TABLE feedback_submit (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_feedbackSubmit" PRIMARY KEY,
      type varchar,
      last_update date NOT NULL,
      stars integer,
      objections varchar,
      text_comment varchar,
      form_id varchar,
      country_code varchar
    );

    CREATE UNIQUE INDEX "form_id_IX" ON feedback_submit (form_id);
  `
)
