export default "## 1. WILLKOMMEN\n" +
  "Wir möchten Ihnen dafür danken, dass Sie sich für die Nutzung von Vexl entschieden haben. Wir wissen, dass Sie es kaum erwarten können, es sofort zu benutzen, aber wir bitten Sie, sich ein paar Minuten Zeit zu nehmen, um zuerst die Nutzungsbedingungen durchzulesen. Wir wissen Ihre Zeit zu schätzen und versprechen Ihnen, dass wir uns so kurz wie möglich fassen werden. Wenn Sie mit allem, was Sie hier lesen, einverstanden sind, können Sie mit der Nutzung von Vexl.\n" +
  "## 2. PARTEIEN\n" +
  "Beginnen wir mit der Einleitung, damit Sie wissen, wer sich hinter den in diesem Dokument häufig verwendeten Begriffen “wir” und “Sie” verbirgt.\n " +
  "Wir sind die Handelsgesellschaft Vexl s.r.o. mit Sitz in Kundratka 2359/17a, Libeň, 180 00 Prag 8, Tschechische Republik. Obwohl diese Informationen für Sie wahrscheinlich ausreichend sind, müssen wir laut Gesetz auch erwähnen, dass unsere Id. Nr. 172 70 642 lautet und wir im Handelsregister des Handelsgerichts in Prag unter der Aktennummer 369216 eingetragen sind. Mit “Sie” meinen wir jeden, ob natürliche oder juristische Person, der Vexl in irgendeiner Weise nutzt.\n " +
  "Es versteht sich wohl von selbst, aber Ihre Rechtsfähigkeit darf nicht so weit eingeschränkt sein, dass sie Sie daran hindern könnte, diese Nutzungsbedingungen zu akzeptieren und Vexl zu nutzen. Der Einfachheit halber vereinbaren wir einfach, dass Sie mindestens 18 Jahre alt sein müssen, um Vexl zu nutzen.\n" +
  "## 3. ÜBER VEXL\n" +
  "Um es einfach auszudrücken, ist Vexl ein Dienst (der eine Anwendung umfasst), der es Nutzern, die am Kauf oder Verkauf von Bitcoin interessiert sind, ermöglicht, miteinander in Verbindung zu treten, um ihre Angebote zu besprechen und den Handel zu vereinbaren. Darüber hinaus sammelt und speichert Vexl so gut wie keine Informationen über die Nutzer. Sobald die Nutzer miteinander verbunden sind, können sie den potenziellen Handel über einen privaten und sicheren (Ende-zu-Ende-verschlüsselten) Chat besprechen." +
  "**Wichtiger Hinweis: Vexl selbst bietet keine Instrumente an, um Bitcoin-Transaktionen zwischen den Nutzern zu erleichtern. Wir überwachen nicht, ob ein Handel zwischen unseren Nutzern stattgefunden hat. Das einzige Ziel von Vexl ist es, den Nutzern eine sichere und einfach zu bedienende Plattform zur Verfügung zu stellen, um sich gegenseitig zu finden, zu kontaktieren und die Bedingungen des Handels zu besprechen.**\n " +
  "Aus den oben genannten Gründen können wir auch keine Bestätigungen für die Transaktionen zwischen den Nutzern ausstellen und wir können erst recht keine Rechnungen im Namen der Nutzer ausstellen. Wenn Sie eine solche Bestätigung benötigen, müssen Sie dies der anderen Partei Ihres Geschäfts mitteilen.\n" +
  "## 4. BENUTZERKONTO \n" +
  "Um Ihr Benutzerkonto sicher und privat zu halten, haben wir uns für einen neuen Ansatz entschieden. Anstatt ein herkömmliches Benutzerkonto zu erstellen und alle zugehörigen Daten auf unseren Servern zu speichern, haben wir beschlossen, dass die meisten sensiblen Daten lokal auf Ihrem Gerät gespeichert werden und dass Ihr Benutzerkonto nur mit einem so genannten privaten Schlüssel zugänglich ist, der von Vexl als Teil des Onboarding-Verfahrens lokal auf Ihrem Gerät erstellt und gespeichert wird. Dies ist sehr wichtig, denn es bedeutet, dass Ihr Konto nur von Ihrem Gerät aus zugänglich ist und sobald der private Schlüssel gelöscht wird, kann niemand mehr auf das Benutzerkonto zugreifen." +
  "**Wichtiger Hinweis: Ihr privater Schlüssel ist für den Zugriff auf Ihr Benutzerkonto und die damit verbundenen Daten unerlässlich. Wenn Sie Ihr Telefon verlieren, die Festplatte Ihres Telefons formatieren, Vexl deinstallieren oder sich einfach nur von Vexl abmelden, geht Ihr privater Schlüssel verloren, und Ihr ursprüngliches Benutzerkonto einschließlich aller zugehörigen Daten kann nicht wiederhergestellt werden.**\n" +
  "Um Ihr Benutzerkonto zu erstellen, verifizieren wir Ihre Telefonnummer, indem wir Ihnen einen Verifizierungscode schicken. Sie erklären sich damit einverstanden, Textnachrichten (von uns oder unseren Drittanbietern) mit Verifizierungscodes zu erhalten, um das Onboarding-Verfahren abzuschließen, und Sie stimmen zu, dass Sie berechtigt sind, die Telefonnummer für diesen Zweck zu verwenden.\n" +
  "Obwohl Sie für den Zugang zu Vexl kein Passwort einrichten müssen, empfehlen wir Ihnen, dies zu tun. Bei der Wahl Ihres Passworts empfehlen wir Ihnen außerdem, keine Passwörter zu verwenden, die in Anwendungen von Drittanbietern verwendet werden. Es empfiehlt sich auch, das Passwort häufig zu ändern, um Ihr Benutzerkonto sicher zu halten. Alternativ können Sie auch FaceID einrichten, um auf Vexl.\n" +
  "Das Benutzerkonto ist Ihnen gewidmet, und Sie sind für alle Aktivitäten verantwortlich, die auf oder über das Benutzerkonto erfolgen, daher ist es wichtig, dass Sie Ihr Passwort und die für den Zugriff auf das Benutzerkonto verwendeten Geräte sicher aufbewahren. Dies schützt nicht nur Sie, sondern auch alle anderen Benutzer von Vexl, die nicht wissen können, wer tatsächlich in Ihrem Vexl-Konto angemeldet ist.\n" +
  "## 5. BENUTZERKONTAKTE\n" +
  "Vexl erlaubt es Ihnen nur, sich mit Ihren Freunden (Kontakte 1. Grades) oder mit Personen zu verbinden, mit denen Sie einen gemeinsamen Freund haben (Kontakte 2. Grades). Daher werden Sie im Rahmen des Einführungsprozesses gebeten, die Kontaktdaten Ihrer Freunde entweder aus Ihrem Telefonadressbuch zu importieren, damit Vexl Ihre Kontaktdatenbank mit den Kontaktdaten unserer derzeitigen Nutzer abgleichen kann. Dies erlaubt es Vexl nicht, Änderungen an der Kontaktliste auf Ihrem Telefon vorzunehmen. Die Kontaktdaten bleiben dann verschlüsselt in einem separaten Microservice gespeichert, der nur für die Bearbeitung von Kontaktlisten bestimmt ist und auf den wir keinen Zugriff haben." +
  "**Wichtiger Hinweis: Wie andere Daten auch, werden die Kontaktinformationen von Vexl lokal auf Ihrem Gerät verschlüsselt, so dass wir sie nicht lesen können, wenn sie an unseren Microservice übertragen werden. Wir suchen Ihre Kontakte 1. und 2. Grades ausschließlich durch den Vergleich der verschlüsselten Daten (Hashes) miteinander, ohne die eigentlichen zugrundeliegenden Kontaktinformationen zu kennen.**\n" +
  "## 6. ANGEBOTE UND CHAT\n" +
  "Die Veröffentlichung von Angeboten zum Kauf oder Verkauf von Bitcoin und die Erleichterung der Verbindung mit den Nutzern, die an solchen Angeboten interessiert sind, ist die Hauptfunktion von Vexl. Abhängig von den Parametern des Angebots ist es entweder nur für Ihre Kontakte ersten Grades oder auch für die Kontakte zweiten Grades sichtbar. Das Angebot wird für den jeweiligen Nutzer mit seinem öffentlichen Schlüssel verschlüsselt, so dass kein anderer Nutzer es sehen kann.\n" +
  "**Wichtiger Hinweis: Die Nutzer kennen die Identität des anbietenden Nutzers erst dann, wenn der anbietende Nutzer sie aktiv preisgibt. Sie sehen jedoch anonyme Informationen über die Verbindung zwischen den Nutzern (z. B. wie viele gemeinsame Freunde es gibt usw.).**\n" +
  "Der Nutzer kann beantragen, mit dem Nutzer, der das Angebot macht, verbunden zu werden. Wird eine Verbindung vom anbietenden Nutzer akzeptiert, wird ein Chat zwischen den Nutzern gestartet. Innerhalb des Chats können sich die Nutzer gegenseitig auffordern, ihre Identität preiszugeben. Dies ist absolut freiwillig und Sie können jederzeit ablehnen. Wenn Sie Ihre Identität einmal preisgegeben haben, kann dies nicht mehr rückgängig gemacht werden.\n" +
  "Die Nachrichten innerhalb des Chats werden verschlüsselt mit den öffentlichen Schlüsseln der beiden am Chat beteiligten Nutzer übertragen. Die Nachrichten werden lokal auf den Handys der beiden Nutzer gespeichert, wo sie mit den jeweiligen privaten Schlüsseln entschlüsselt werden können. Wir übermitteln die Nachrichten lediglich zwischen den Nutzern und speichern sie nicht dauerhaft auf unseren Servern (und selbst wenn wir es täten, könnten wir sie ohnehin nicht lesen, da sie verschlüsselt sind).\n" +
  "**Wichtiger Hinweis: Die Chatnachrichten werden von uns nicht gesichert. Sobald der Chat geschlossen ist, können die Nachrichten nicht wiederhergestellt werden. Wenn Sie sich mit dem anderen Nutzer über wichtige Details zu Ihrem Handel einigen, empfehlen wir, den Chat erst zu schließen, wenn der Handel erfolgreich abgewickelt wurde.**" +
  "## 7. PERSÖNLICHE DATEN\n" +
  "Wir versichern Ihnen, dass die Erfassung Ihrer persönlichen Daten (z. B. die Daten, die Sie bei der Erstellung Ihres Benutzerkontos angeben) im Zusammenhang mit der Nutzung von Vexl so begrenzt wie möglich ist. Die meisten Informationen werden lokal gespeichert und in verschlüsselter Form an andere Nutzer übermittelt, so dass wir sie nicht lesen können, selbst wenn wir es wollten." +
  "Wenn eine Erhebung, Speicherung und Verarbeitung Ihrer personenbezogenen Daten tatsächlich erfolgt, wird dies stets transparent in einer gesonderten Regelung zum Umgang mit personenbezogenen Daten von Vexl-Nutzern (Vexl-Datenschutzrichtlinie) beschrieben, der Sie im nächsten Schritt des Onboarding-Verfahrens zustimmen müssen.\n" +
  "## 8. ANWENDUNG UND LIZENZEN\n" +
  "Die Vexl-Anwendung stellt die einzige Möglichkeit dar, auf die Vexl-Dienste zuzugreifen, und ist daher ein wesentlicher Bestandteil von Vexl. Von Zeit zu Zeit kann unsere Vexl-Anwendung aktualisiert werden. In solchen Fällen informieren wir Sie in der Regel über ein Pop-up-Fenster in der Anwendung, dass eine neue Aktualisierung verfügbar ist. Sie verpflichten sich, die Anwendung immer zu aktualisieren, bevor Sie sie weiter nutzen, um eine korrekte Funktionalität zu gewährleisten.\n" +
  "Die Nutzung der Vexl-Anwendung unterliegt der GNU General Public License Version 3 (GPLv3). Bitte bedenken Sie, dass wir die Vexl-Anwendung oder Teile davon auch unter einer proprietären Lizenz lizenzieren können.\n" +
  "Ungeachtet der Bestimmungen in diesen Nutzungsbedingungen bleiben wir Eigentümer aller Urheberrechte, Marken, Logos, Patente und anderer geistiger Eigentumsrechte, die mit Vexl verbunden sind.\n" +
  "## 9. VERHALTENSKODEX\n" +
  "**Verhalten gegenüber anderen Nutzern**\n" +
  "Wie Sie inzwischen wissen, können Sie über Vexl mit anderen Nutzern kommunizieren. Auch wenn wir nur die verschlüsselte Kommunikation zwischen den Nutzern übermitteln und keine Möglichkeit haben, diese zu überprüfen, bitten wir Sie dennoch, sich anständig zu benehmen. Wir gehen davon aus, dass unsere Nutzer verstehen, was wir meinen, wenn wir von angemessenem Verhalten sprechen, und obwohl wir es gerne dabei belassen würden, schreibt das Gesetz vor, dass wir präziser sein müssen, also lassen Sie es uns kurz machen:\n" +
  "**Du darfst nicht (i)** die Rechte anderer Nutzer missbrauchen oder verletzen, einschließlich der Privatsphäre, der Öffentlichkeit, des geistigen Eigentums oder anderer Eigentumsrechte; **(ii)** anderen Nutzern keine Inhalte senden, die illegal, obszön, verleumderisch, bedrohlich, einschüchternd, belästigend, hasserfüllt, rassistisch oder ethnisch beleidigend sind oder ein Verhalten fördern, das illegal oder anderweitig unangemessen ist; **(iii)** an andere Nutzer falsche oder irreführende Informationen zu senden; (iv) sich bei der Kommunikation mit anderen Nutzern als andere auszugeben; oder (v) an andere Nutzer Viren oder anderen schädlichen Computercode zu senden. \n" +
  "**Verhalten uns gegenüber**\n" +
  "Außerdem bitten wir Sie, uns gegenüber respektvoll zu sein und Vexl nicht für ungesetzliche Aktivitäten oder in einer Weise zu nutzen, die uns schaden könnte. Auch hier würden wir es gerne dabei belassen, aber das Gesetz schreibt uns vor, genauer zu sein, also lassen Sie uns noch einmal die ausreichenden Details auflisten:\n" +
  "**Sie dürfen (i)** Vexl nicht für andere als legale, autorisierte und akzeptable Zwecke in Übereinstimmung mit diesen Nutzungsbedingungen nutzen, **(ii)** Vexl nicht in einer Weise aufrufen, nutzen, verändern, verbreiten oder ausnutzen, die uns schaden könnte (Einschleusen von Viren oder anderem bösartigen oder schädlichen Material, Versuch, sich unbefugten Zugang zu unseren Systemen zu verschaffen, Störung der Integrität von Vexl usw.), **(iii)** die Rechte unseres Unternehmens, einschließlich des geistigen Eigentums oder anderer Eigentumsrechte, missbrauchen oder verletzen.\n" +
  "**Verletzung von Zusicherungen**\n" +
  "Wenn Sie etwas in diesen Nutzungsbedingungen zusichern oder zustimmen, nehmen wir Sie beim Wort. Wenn wir also später erfahren, dass eine Ihrer Zusicherungen falsch war, gilt dies als Verstoß gegen diese Nutzungsbedingungen.\n" +
  "## 10. VERSTÖSSE MELDEN\n" +
  "Wenn Sie feststellen, dass Inhalte auf Vexl Ihre geistigen Eigentumsrechte oder moralischen Rechte (einschließlich der Rechte auf Privatsphäre und Porträt) verletzen oder als eine andere Verletzung geltender Gesetze oder dieser Nutzungsbedingungen angesehen werden können, melden Sie den Verstoß bitte über die E-Mail-Adresse: [support@vexl.it](mailto:support@vexl.it).\n" +
  "Es kann sein, dass wir zusätzliche Informationen und/oder Materialien (wie z.B. Ihre persönlichen Daten und Beweise für den Verstoß) anfordern, die für die Beurteilung Ihrer Meldung erforderlich sind, und in diesem Fall erklären Sie sich bereit, unseren zusätzlichen Anfragen in vollem Umfang nachzukommen. Es versteht sich von selbst, dass die Meldung nur dann von uns bewertet werden kann, wenn Sie vollständig kooperieren und alle angeforderten Materialien und/oder Informationen zur Verfügung stellen.\n" +
  "Bitte beachten Sie, dass wir, selbst wenn der Verstoß auftritt und gemeldet wird, nur sehr begrenzte Möglichkeiten haben, die Inhalte innerhalb von Vexl zu entfernen, da die Inhalte lokal auf den Geräten der Nutzer gespeichert werden (und wir diese absolut nicht auf der Suche nach schädlichen Inhalten durchsuchen können; außerdem sind die Inhalte verschlüsselt) und nur in verschlüsselter Form zwischen den Nutzern übertragen werden (und nur von den Nutzern entschlüsselt werden können, an die sie gerichtet sind, nicht von uns).\n" +
  "## 11. VERFÜGBARKEIT \n" +
  "Wir sind stets bemüht, einen kontinuierlichen, ununterbrochenen Betrieb unserer Dienste zu gewährleisten, so dass Sie jederzeit auf Vexl zugreifen und es nutzen können. Aufgrund von Wartungsarbeiten, Reparaturen, außergewöhnlichen Ausfällen oder aus anderen Gründen kann es jedoch vorkommen, dass Vexl nicht verfügbar ist. Daher können wir nicht immer eine völlig ununterbrochene Verfügbarkeit garantieren." +
  "## 12. HAFTUNGS- UND GEWÄHRLEISTUNGSBESCHRÄNKUNG\n" +
  "Zusammenfassend:\n" +
  "- Vexl wird Ihnen im Ist-Zustand und nach Verfügbarkeit ohne jegliche Garantie zur Verfügung gestellt.\n" +
  "- Wir haften nicht für Schäden im Zusammenhang mit Ihrer Nutzung oder der Unfähigkeit zur Nutzung von Vexl.\n" +
  "- Wir sind nicht verantwortlich für Verstöße gegen die zwischen den Benutzern über Vexl vereinbarten Bedingungen.\n" +
  "Im Detail:\n" +
  "Wir haben Vexl entwickelt und betreiben es mit einem angemessenen Maß an Fachkenntnis und Sorgfalt, und wir hoffen, dass Sie Freude an der Nutzung haben werden; beachten Sie jedoch, dass es Ihnen nach wie vor auf der Basis des Ist-Zustandes und der Verfügbarkeit angeboten wird, und wir lehnen daher ausdrücklich jegliche ausdrückliche oder stillschweigende Gewährleistung in diesem Zusammenhang ab. \n" +
  "Wir haften unter keinen Umständen für direkte, indirekte, besondere oder Folgeschäden, Strafschadensersatz oder sonstige Schäden und Kosten, einschließlich, aber nicht beschränkt auf entgangenen Gewinn, entgangene Einnahmen oder entgangene Geschäftschancen, die sich aus oder im Zusammenhang mit Ihrem Zugang und Ihrer Nutzung oder der Unmöglichkeit des Zugangs und der Nutzung von Vexl ergeben.\n" +
  "Darüber hinaus verzichten Sie hiermit im größtmöglichen Umfang, der nach geltendem Recht zulässig ist, auf jegliche Schadensersatzansprüche, die Sie gegen uns im Zusammenhang mit Ihrer Nutzung von Vexl oder der Unfähigkeit, Vexl zu nutzen, haben könnten.\n" +
  "Sie verzichten insbesondere auf Schäden, die im Zusammenhang mit mit anderen Nutzern von Vexl vereinbarten Geschäften entstehen. Sie sind allein für die Daten- und Mobilfunkgebühren und -steuern verantwortlich, die mit den Geräten verbunden sind, auf denen Sie Vexl nutzen.\n" +
  "Sollten sich die obigen Gewährleistungs- und Haftungsausschlüsse als nichtig, ungültig oder anderweitig nicht durchsetzbar erweisen, erklären Sie sich damit einverstanden, dass unsere Gesamthaftung für jegliche Ansprüche, die sich aus diesen Nutzungsbedingungen oder in Verbindung damit ergeben, auf den größtmöglichen Umfang beschränkt ist, den das geltende Recht zulässt.\n" +
  "## 13: FINANZIELLE RISIKEN\n" +
  "Auch wenn der Handel zwischen unseren Nutzern uns nichts angeht, wie wir wiederholt erklärt haben, fühlen wir uns dennoch verpflichtet, Sie über potenzielle Risiken im Zusammenhang mit Kryptowährungen zu informieren (es ist wohl eher so, dass wir gesetzlich dazu verpflichtet sind)." +
  "Das Wichtigste zuerst: Die Informationen auf Vexl stellen unter keinen Umständen eine Finanz-, Investitions- oder professionelle Beratung dar, es sei denn, dies wird ausdrücklich erwähnt. Sie tragen die alleinige Verantwortung für Ihre Entscheidungen in Bezug auf das Lagern, Kaufen, Verkaufen, Tauschen, Senden und Empfangen von Bitcoin, und Sie müssen immer Ihre finanziellen Verhältnisse und die damit verbundenen Risiken berücksichtigen, bevor Sie Bitcoin erwerben.\n" +
  "Sie versichern, dass Sie alle Risiken verstehen, die mit dem Kauf, Verkauf und Tausch von Bitcoin verbunden sind, einschließlich der Tatsache, dass Bitcoin-Transaktionen irreversibel sind. Sie versichern, dass Ihnen bewusst ist, dass der Wert von Bitcoin extrem volatil sein kann und dass sein Wechselkurs in Bezug auf andere Kryptowährungen oder Fiat-Währungen erheblich schwanken kann, was zu erheblichen und plötzlichen Wertverlusten Ihres Vermögens führen kann.\n" +
  "Sie erkennen hiermit an, dass Sie allein dafür verantwortlich sind, die notwendigen Informationen über steuerliche oder ähnliche Verpflichtungen einzuholen, die sich im Zusammenhang mit den eingereichten Transaktionen ergeben, und die korrekten Steuerbeträge einzubehalten, einzuziehen, zu melden und an die zuständigen Steuerbehörden abzuführen.\n" +
  "Sie erkennen an, dass nicht alle mit der Verwendung von Kryptowährungen verbundenen Risiken in diesen Nutzungsbedingungen genannt werden.\n" +
  "**Wichtiger Hinweis: Vexl zeigt den aktuellen Bitcoin-Kurs an, um den Nutzern die Nutzung zu erleichtern. Es gibt jedoch keinen allgemein akzeptierten Preis für Bitcoin und die Preise unterscheiden sich in der Regel zwischen verschiedenen Kryptowährungsbörsen. In Vexl zeigen wir Ihnen den Durchschnittspreis von Bitcoin, der von CoinGecko ([https://coingecko.com](https://coingecko.com)) bereitgestellt wird.**\n" +
  "## 14. TERMINATION\n" +
  "Wir werden es immer bedauern, Sie gehen zu sehen, aber wenn Sie sich entscheiden, Vexl nicht mehr zu benutzen, werden wir Ihre Entscheidung respektieren. Ihr Benutzerkonto kann ganz einfach gelöscht werden, indem Sie auf die Schaltfläche “Abmelden” unter der Oberfläche des Benutzerkontos tippen. Nach der Abmeldung können keine Daten, die mit dem ursprünglichen Benutzerkonto in Verbindung stehen, wiederhergestellt werden.\n" +
  "**Wichtiger Hinweis: Wenn Sie sich abmelden wollen, seien Sie bitte vorsichtig, denn durch das Abmelden wird Ihr Benutzerkonto effektiv gelöscht. Ein solcher Vorgang ist nicht rückgängig zu machen, d. h., wenn Sie sich entscheiden, Vexl in Zukunft wieder zu nutzen, können Sie keine Daten wiederherstellen, die mit Ihrem ursprünglichen Benutzerkonto verknüpft sind, und Sie müssen dasselbe Onboarding-Verfahren wie jeder neue Benutzer durchlaufen.**\n" +
  "Wir behalten uns außerdem ausdrücklich das Recht vor, den Zugang zu Vexl für Nutzer, die in bestimmten Ländern ansässig sind, oder für Staatsangehörige bestimmter Länder vor allem aus regulatorischen Gründen auszusetzen oder dauerhaft zu verweigern (wir können Ihren Standort oder Ihre Nationalität auch indirekt z. B. über einen Ländercode, den App-Store oder Ihre Telefonnummer identifizieren).\n" +
  "Schließlich behalten wir uns auch das Recht vor, Vexl vollständig einzustellen. In diesem Fall werden wir Sie mindestens dreißig (30) Tage im Voraus informieren. Danach steht es uns frei, Vexl einzustellen, und Sie können nicht mehr auf Ihr Benutzerkonto zugreifen.\n" +
  "## 15. NACHRICHTEN\n" +
  "**Unsere Nachrichten an Sie:** Wir werden Sie nicht zu sehr belästigen, aber gelegentlich müssen wir Sie vielleicht kontaktieren. In diesem Fall werden wir eine Push-Benachrichtigung verwenden, die Ihnen bei der Anmeldung in Ihrem Benutzerkonto zur Verfügung steht.\n" +
  "## 16. ANWENDBARES RECHT\n" +
  "Ihre Nutzung von Vexl sowie diese Nutzungsbedingungen und alle damit zusammenhängenden Fragen, einschließlich etwaiger Streitigkeiten zwischen Ihnen und uns, unterliegen den Gesetzen der Tschechischen Republik, ohne Rücksicht auf kollisionsrechtliche Grundsätze.\n" +
  "Nur für Verbraucher: Wir sind verpflichtet, Sie darauf hinzuweisen, dass diese Rechtswahlklausel Ihnen, wenn Sie ein Verbraucher sind, nicht Ihre Rechte nach zwingenden Bestimmungen des Rechts des Landes Ihres gewöhnlichen Aufenthalts entzieht, wenn dieses Recht ansonsten gemäß Artikel 6 Absatz 1 der Verordnung (EG) Nr. 593 / 2008 des Europäischen Parlaments und des Rates vom 17. Juni 2008 über das auf vertragliche Schuldverhältnisse anzuwendende Recht (Rom I) anwendbar wäre.\n" +
  "## 17. STREITBEILEGUNG\n" +
  "Wir versuchen immer, alle Probleme friedlich zu lösen, und bitten Sie, das Gleiche zu tun. Daher verpflichten Sie sich, uns über alle Streitigkeiten zu informieren, die sich aus oder in Verbindung mit diesen Nutzungsbedingungen ergeben, und Sie verpflichten sich, stets eine außergerichtliche Streitbeilegung anzustreben, bevor Sie den Streit vor Gericht bringen.\n" +
  "Manchmal ist eine außergerichtliche Streitbeilegung jedoch einfach nicht möglich. In diesem Fall werden alle Streitigkeiten, die in irgendeiner Weise mit diesen Nutzungsbedingungen zusammenhängen, endgültig vor den Gerichten der Tschechischen Republik entschieden, die für den Sitz unseres Unternehmens zuständig sind.\n" +
  "**Nur für Verbraucher:** Wir sind verpflichtet, Sie darüber zu informieren, dass Sie im Falle von Streitigkeiten das Recht haben, eine außergerichtliche Beilegung durch das Tschechische Telekommunikationsamt mit Sitz in Prag 9, Sokolovská 219, Id. Nr. 701 06 975, Internetadresse ([https://www.ctu.eu/out-court-dispute-resolution](https://www.ctu.eu/out-court-dispute-resolution)) für Streitigkeiten im Zusammenhang mit elektronischer Kommunikation und durch das Tschechische Gewerbeaufsichtsamt mit Sitz in Štěpánská 567/15, 120 00 Prag 2, Id. Nr. 000 20 869, Webadresse [https://adr.coi.cz/cs](https://adr.coi.cz/cs) für alle anderen Streitigkeiten. Sie können auch eine Plattform zur außergerichtlichen Streitbeilegung nutzen, die sich auf der Website [http://ec.europa.eu/consumer/odr](http://ec.europa.eu/consumer/odr) befindet." +
  "## 18. ÄNDERUNGEN\n" +
  "**Betreiber**: Sie erklären sich mit einem künftigen Wechsel des Betreibers der Vexl-Dienste gemäß diesen Nutzungsbedingungen einverstanden (Abtretung des durch diese Nutzungsbedingungen begründeten Vertrags). Im Falle eines solchen Wechsels werden wir Sie stets benachrichtigen.\n" +
  "**Dienstleistungsbedingungen**: Wir können diese Nutzungsbedingungen oder eine zusätzliche Bedingung, die für Vexl gilt (z. B. die Datenschutzrichtlinie), von Zeit zu Zeit ändern oder ergänzen, und wenn wir dies tun, müssen wir Sie bitten, sie durchzulesen und ihnen erneut zuzustimmen. Wir wissen, dass dies für Sie unangenehm ist, und versprechen, dies nicht allzu oft zu tun. Wenn Sie Vexl weiterhin nutzen, bestätigen Sie damit, dass Sie unsere aktualisierten Nutzungsbedingungen akzeptieren.\n"
