export default "## 1. VÍTEJTE\n" +
  "Rádi bychom Vám poděkovali, že jste se rozhodli" +
  "používat právě Vexl. Víme, že se už nemůžete dočkat, až se do něj poprvé" +
  "přihlásíte, ale ještě před tím bychom Vás rádi požádali, abyste nám" +
  "věnovali několik minut Vašeho času a přečetli si tyto Smluvní podmínky." +
  "Víme, že Váš čas je cenný, a proto slibujeme, že naše dokumenty budou vždy" +
  "maximálně stručné. Pokud souhlasíte se vším, co jste si zde přečetli," +
  "můžete se pustit do používání Vexlu.\n" +
  "## 2. SMLUVNÍ STRANY\n" +
  'Nejprve se pojďme vzájemně představit, abyste věděli, kdo se skrývá pod pojmy "my" a "Vy", které se v tomto dokumentu často vyskytují.\n' +
  "„My“ jsme obchodní společnost **Vexl s.r.o.** se sídlem Kundratka 2359/17a, Libeň, 180 00 Praha 8, Česká Republika. Toto by pro Vás pravděpodobně byla dostatečná informace, zákon nám však ukládá, abychom ještě uvedli, že naše identifikační číslo (IČO) je 172 70 642 a že jsme zapsáni v obchodním rejstříku vedeném Městským soudem v Praze, oddíl C, vložka 369216.\n\n" +
  "Pojmem „Vy“ máme na mysli kohokoliv, kdo Vexl jakýmkoliv způsobem používá, nehledě na to, zda jste fyzická nebo právnická osoba.\n\n" +
  "Asi je to samozřejmé, ale Vaše svéprávnost (způsobilost právně jednat) nesmí být omezena do té míry, že by Vám to mohlo bránit v souhlasu s těmito Smluvními podmínkami a používání Vexlu. Pro zjednodušení se zkrátka dohodněme, že pro používání Vexlu Vám musí být alespoň 18 let.\n" +
  "## 3. CO JE VEXL?\n" +
  "Zjednodušeně řečeno, Vexl je služba (jejíž součástí je aplikace), která umožňuje uživatelům se zájmem o nákup nebo prodej Bitcoinu navázat spojení, diskutovat o svých nabídkách a dohodnout se na obchodech. A co víc, Vexl během celého procesu o uživatelích neshromažďuje a neukládá téměř žádné informace. Jakmile se uživatelé propojí, mohou o možném obchodu komunikovat prostřednictvím soukromého zabezpečeného (end-to-end šifrováním) chatu.\n" +
  "### Důležité upozornění: Vexl jako takový neobsahuje žádné nástroje, které by uživatelům umožňovaly provádět transakce Bitcoinu. Zároveň Vexl ani nesleduje, zda mezi některými z našich uživatelů vůbec došlo k obchodům s Bitcoinem. Jediným účelem Vexlu je poskytnout uživatelům bezpečnou a snadno použitelnou platformu, na které se mohou vzájemně vyhledat, kontaktovat a projednat podmínky případného obchodu.\n" +
  "Z výše uvedených důvodů také nemůžeme vydávat žádná potvrzení o transakcích mezi uživateli a rozhodně nemůžeme jménem uživatelů vystavovat žádné faktury. Pokud takové potvrzení potřebujete, musíte svůj požadavek sdělit uživateli, se kterým obchodujete.\n" +
  "## 4. UŽIVATELSKÝ ÚČET\n" +
  "Abychom zajistili bezpečnost a soukromí Vašeho uživatelského účtu, rozhodli jsme se pro zcela inovativní přístup. Namísto vytváření běžného uživatelského účtu a ukládání všech souvisejících dat na našich serverech jsme se rozhodli, že většina citlivých dat bude uložena lokálně ve Vašem zařízení a že Váš uživatelský účet bude přístupný pouze s pomocí takzvaného privátního klíče, který Vexl vygeneruje a uloží lokálně ve Vašem zařízení při vytvoření uživatelského účtu. To znamená, že Váš účet je přístupný pouze z Vašeho zařízení a jakmile je privátní klíč vymazán, nikdo včetně Vás se k uživatelskému účtu nebude moci přihlásit.\n" +
  "### Důležité upozornění: Váš privátní klíč je nezbytný pro přístup k uživatelskému účtu a souvisejícím datům. Pokud ztratíte svůj mobilní telefon, formátujete disk Vašeho mobilního telefonu, odinstalujete aplikaci Vexl nebo se dokonce jen rozhodnete z aplikace Vexl odhlásit, Váš privátní klíč bude ztracen a Váš původní uživatelský účet včetně všech souvisejících dat nebude možné obnovit.\n" +
  "Při vytvoření Vašeho uživatelského účtu ověříme Vaše telefonní číslo zasláním ověřovacího kódu. Souhlasíte s tím, že obdržíte SMS zprávu (od nás nebo od našich externích partnerů) s ověřovacími kódy pro dokončení procesu registrace a potvrzujete, že jste pro tento účel oprávněni dané telefonní číslo používat.\n\n" +
  "Ačkoli si pro přístup k Vexlu nemusíte nastavovat heslo, důrazně doporučujeme to udělat. Při volbě hesla také doporučujeme nepoužívat znovu hesla používaná v jiných aplikacích. Dobrým nápadem, jak udržet svůj uživatelský účet v bezpečí, může být také častá změna hesla. Pro přístup k aplikaci Vexl si můžete případně také nastavit FaceID.\n\n" +
  "Uživatelský účet je určen pouze Vám a Vy jste tedy odpovědní za všechny činnosti, které se na něm nebo jeho prostřednictvím odehrávají, proto je důležité, abyste své heslo a zařízení používaná k přístupu k uživatelskému účtu zabezpečili. Tím chráníte nejen sebe, ale i všechny ostatní uživatele Vexlu, kteří nemají možnost zjistit, kdo je skutečně přihlášen k Vašemu uživatelskému účtu.\n" +
  "## 5. KONTAKTY UŽIVATELE \n" +
  "Vexl Vám umožňuje spojit se pouze s Vašimi přáteli (kontakty 1. stupně) nebo s lidmi, se kterými máte společného přítele (kontakty 2. stupně). Proto budete v rámci procesu registrace požádáni o import kontaktních údajů Vašich přátel, buď z adresáře Vašeho mobilního telefonu, aby Vexl mohl porovnat Vaši databázi kontaktů s kontaktními údaji našich současných uživatelů. Vexl přitom nemůže provádět jakékoliv změny v seznamu kontaktů ve Vašem mobilním telefonu. Kontaktní údaje poté zůstanou uloženy zašifrované (a pro nás tedy nečitelné) v naší samostatné mikroslužbě určené pouze pro ukládání těchto zašifrovaných seznamů kontaktů.\n" +
  "### Důležité upozornění: Stejně jako u ostatních údajů budou kontaktní údaje zašifrovány Vexlem lokálně ve Vašem zařízení a pro nás jsou tedy nečitelné. Vaše kontakty 1. a 2. stupně vyhledáváme výhradně vzájemným porovnáním zašifrovaných dat (hashů), aniž bychom museli znát podkladové kontaktní údaje.\n" +
  "## 6. NABÍDKY A CHAT \n" +
  "Hlavní funkcí Vexlu je zveřejňování nabídek na nákup nebo prodej Bitcoinu a zprostředkování kontaktu mezi uživateli, kteří mají o tyto nabídky zájem. V závislosti na parametrech nabídky je tato viditelná buď pro kontakty 1. stupně nebo pro kontakty 2. stupně. Nabídka je pro dané uživatele zašifrována pomocí jejich veřejných klíčů, takže ji žádný jiný uživatelé nevidí.\n" +
  "### Důležité upozornění: Uživatelé neznají identitu nabízejícího, dokud ji nabízející sám aktivně neprozradí. Vidí však anonymní informace o vzájemném spojení (například kolik mají společných přátel atd.)\n" +
  "Uživatel může požádat o propojení s uživatelem, který činí nabídku. Pokud uživatel, který nabídku učinil, spojení přijme, zahájí se mezi uživateli chat. V rámci tohoto chatu mohou uživatelé požadovat, aby si navzájem prozradili svou identitu. Toto je zcela dobrovolné a vždy můžete odmítnout. Odhalení identity je nevratné.\n\n" +
  "Zprávy v rámci chatu jsou zašifrované pomocí veřejných klíčů obou uživatelů, kteří se chatu účastní. Zprávy jsou uloženy lokálně v mobilních telefonech obou uživatelů, kde je lze dešifrovat pomocí jejich soukromých klíčů. Z naší strany zprávy pouze přenášíme a neukládáme je trvale na naše servery (vedle toho i kdybychom je ukládali, nemohli bychom je přečíst, protože jsou zašifrované).\n" +
  "### Důležité upozornění: Zprávy v chatu nejsou z naší strany zálohovány. Po ukončení chatu nelze zprávy obnovit. Pokud se s druhým uživatelem dohodnete na důležitých detailech týkajících se Vašeho obchodu, doporučujeme chat neukončovat, dokud není obchod úspěšně dokončen.\n" +
  "## 7. OSOBNÍ ÚDAJE\n" +
  "Rádi bychom Vás ubezpečili, že shromažďování Vašich osobních údajů (např. údajů poskytnutých při vytváření uživatelského účtu) v souvislosti s používáním Vexlu je maximálně omezeno. Většina informací se ukládá lokálně a ostatním uživatelům se přenášejí v zašifrované podobě, takže je navíc nemůžeme přečíst ani kdybychom chtěli.\n\n" +
  "Pokud k nějakému shromažďování, ukládání a nakládání s Vašimi osobními údaji skutečně dojde, bude to vždy transparentně popsáno v samostatném souboru podmínek pro nakládání s osobními údaji uživatelů Vexl (Zásady ochrany osobních údajů Vexl), k souhlasu s nimiž budete v dalším kroku procesu registrace vyzváni.\n" +
  "## 8. APLIKACE A LICENCE\n" +
  "Aplikace Vexl představuje jediný způsob přístupu ke službám Vexl, a je tedy nedílnou součástí Vexlu. Aplikace může být čas od času aktualizována. V takových případech Vás obvykle prostřednictvím vyskakovacího okna v aplikaci informujeme, že je k dispozici nová aktualizace. Před dalším používáním aplikaci musíte vždy aplikaci aktualizovat, aby byla zajištěna její správná funkčnost.\n\n" +
  "Používání aplikace Vexl se řídí licencí GNU General Public License verze 3 (GPLv3). Mějte prosím na paměti, že aplikaci Vexl nebo její část můžeme licencovat také pod jinou vlastní (např. uzavřenou) licencí.\n\n" +
  "Bez ohledu na cokoli uvedené v těchto Smluvních podmínkách si vyhrazujeme vlastnictví všech autorských práv, ochranných známek, log, patentů a dalších práv duševního vlastnictví spojených s Vexlem.\n\n" +
  "## 9. KODEX CHOVÁNÍ\n" +
  "### Chování vůči ostatním uživatelům\n" +
  "Jak už víte, Vexl Vám umožňuje komunikovat s ostatními uživateli. Přestože komunikaci mezi uživateli přenášíme výhradně v zašifrované podobě a nemáme možnost ji kontrolovat, žádáme Vás, abyste zachovávali určité standardy chování. Věříme, že naši uživatelé chápou, co tím máme na mysli, a přestože bychom to rádi nechali tak, zákon nám ukládá, abychom byli konkrétnější, takže si to pojďme říct:\n\n" +
  "**Nesmíte (i)** zneužívat nebo porušovat práva jiných uživatelů, včetně práv na soukromí, práva na ochranu osobnosti, práva duševního vlastnictví nebo jiná vlastnická práva; **(ii)** posílat jiným uživatelům obsah, který je nezákonný, obscénní, hanlivý, výhružný, zastrašující, obtěžující, nenávistný, rasově nebo etnicky urážlivý, nebo podněcovat k jednání, které by bylo nezákonné nebo jinak nevhodné; **(iii)** zasílat ostatním uživatelům jakékoli nepravdivé nebo zavádějící informace; **(iv)** vydávat se při komunikaci s ostatními uživateli za jiné osoby; nebo **(v)** zasílat ostatním uživatelům viry nebo jiné škodlivé počítačové kódy.\n" +
  "### Chování vůči nám\n" +
  "Současně Vás žádáme, abyste k nám byli ohleduplní a nepoužívali Vexl k nezákonným aktivitám nebo způsobem, který by nás mohl poškodit. Opět bychom to nejraději nechali takto, ale zákon nám ukládá, abychom byli konkrétnější, takže si opět pojďme uvést dostatečné podrobnosti:\n" +
  "**Nesmíte (i)** používat Vexl jinak než k zákonným, oprávněným a přijatelným účelům v souladu s těmito Smluvními podmínkami, **(ii)** zpřístupňovat, používat, upravovat, distribuovat nebo zneužít Vexl způsobem, který by nás mohl poškodit" +
  "(šíření virů nebo jiného nežádoucího či škodlivého obsahu, pokus o získání neoprávněného přístupu do našich systémů, narušení integrity Vexl atd.), **(iii)** zneužívat nebo porušovat práva naší společnosti, včetně práv duševního vlastnictví nebo jiných vlastnických práv.\n" +
  "### Porušení prohlášení \n" +
  "Pokud v těchto Smluvních podmínkách něco prohlásíte nebo s něčím souhlasíte, bereme Vás za slovo, takže pokud se později dozvíme, že některé z Vašich prohlášení podle těchto Smluvních podmínek bylo nepravdivé, budeme to považovat za porušení těchto Smluvních podmínek.\n" +
  "## 10. HLÁŠENÍ PORUŠENÍ\n" +
  "Pokud zjistíte, že jakýkoli obsah v rámci Vexlu porušuje Vaše práva duševního vlastnictví, osobnostní práva (včetně práva na soukromí a práva na zachycení a šíření podoby) nebo může být považován za jakékoli jiné porušení platných právních předpisů nebo těchto Podmínek služby, ohlaste, prosím, toto porušení prostřednictvím e-mailové adresy: [support@vexl.it](mailto:support@vexl.it).\n" +
  "Můžeme si vyžádat další informace a/nebo podklady (například Vaše osobní údaje a důkazy o porušení) potřebné k posouzení Vašeho oznámení a v takovém případě souhlasíte s tím, že budete poskytovat plnou součinnost s našimi dalšími požadavky. Je samozřejmostí, že jakákoliv ohlášení můžeme posoudit pouze v případě, že budete plně spolupracovat a poskytnete nám veškeré požadované podklady a/nebo informace.\n" +
  "Vezměte prosím na vědomí, že i v případě, že k porušení dojde a je ohlášeno, máme jen velmi omezené nástroje k odstranění jakéhokoli obsahu v rámci Vexlu, protože obsah je uložen lokálně v zařízeních uživatelů (a my je rozhodně nemůžeme procházet a hledat v nich jakýkoli škodlivý obsah; obsah je navíc zašifrovaný) a je mezi uživateli přenášen pouze v zašifrované podobě (a dešifrovat jej mohou pouze uživatelé, kterým je určen, nikoli my).\n" +
  "## 11. DOSTUPNOST\n" +
  "Vždy se snažíme zajistit nepřetržitý a nepřerušovaný provoz našich služeb, abyste měli k Vexlu přístup a mohli jej kdykoli užívat. Nicméně z důvodu údržby, oprav, výjimečných výpadků nebo z jiných důvodů se může stát, že Vexl nebude dostupný. Proto nemůžeme vždy zaručit zcela nepřetržitou dostupnost.\n" +
  "## 12. ODPOVĚDNOST A OMEZENÍ ZÁRUKY \n" +
  "V krátkosti:\n" +
  "- Vexl je Vám poskytován na as is a where available bázi bez jakýchkoli záruk.\n" +
  "- Neodpovídáme za žádné škody vzniklé v souvislosti s Vaším používáním nebo nemožností používat Vexl.\n" +
  "- Neneseme odpovědnost za porušení podmínek dohodnutých mezi uživateli prostřednictvím Vexl.\n" +
  "Podrobněji:\n" +
  "Vexl jsme vytvořili a provozujeme s přiměřenou úrovní odbornosti a péče a doufáme, že se Vám jeho užívání bude líbit; nicméně mějte na paměti, že je vám stále nabízen tak, jak je (as is) a bez garance dostupnosti (where available), a proto se výslovně zříkáme jakýchkoli záruk, výslovných nebo předpokládaných, které se k tomuto vztahují.\n" +
  "Za žádných okolností neneseme odpovědnost za jakékoli přímé, nepřímé, zvláštní, následné, sankční nebo jakékoli jiné škody a náklady, zahrnující, mimo jiné, ušlý zisk, ztrátu příjmů nebo ztrátu obchodní příležitosti, které vznikly v důsledku nebo v souvislosti s Vaším přístupem a užíváním nebo nemožností přístupu a užívání Vexlu.\n" +
  "Dále se tímto v plném rozsahu přípustném dle jakýchkoliv platných právních předpisů vzdáváte jakýchkoliv nároků na náhradu škody, které byste vůči nám mohli mít v souvislosti s užíváním Vexlu nebo nemožností jej užívat.\n" +
  "Výslovně se vzdáváte nároku na náhradu škody vzniklé v souvislosti s jakýmikoliv obchody sjednanými s jinými uživateli Vexl. Nesete výhradní odpovědnost za údaje a poplatky mobilního operátora a daně spojené se zařízeními, na kterých používáte Vexl.\n" +
  "Pokud budou výše uvedená omezení záruk a odpovědnosti shledána neplatnými nebo neúčinnými nebo jinak nevymahatelnými, souhlasíte s tím, že naše celková odpovědnost za jakékoli nároky vyplývající z těchto Smluvních podmínek nebo s nimi související je omezena v nejvyšším rozsahu povoleném příslušnými právními předpisy.\n" +
  "## 13. FINANČNÍ RIZIKA\n" +
  "I když nám do obchodování mezi našimi uživateli nic není, jak jsme v těchto Smluvních podmínkách opakovaně uvedli, přesto se cítíme povinni poskytnout Vám poučení o možných rizicích souvisejících s kryptoměnami (abychom byli upřímní, spíše nám to ukládá zákon).\n" +
  "Takže popořadě: V žádném případě nemohou žádné informace v rámci Vexlu představovat finanční, investiční nebo odborné poradenství, pokud to není výslovně uvedeno. Za svá rozhodnutí týkající se ukládání, nákupu, prodeje, směny, zasílání a přijímání Bitcoinu nesete výhradní odpovědnost Vy a vždy musíte před pořízením Bitcoinu zvážit svou finanční situaci a související rizika.\n" +
  "Tímto prohlašujete, že rozumíte všem rizikům spojeným s nákupem, prodejem a směnou Bitcoinu, včetně skutečnosti, že transakce s Bitcoinem jsou nevratné. Prohlašujete, že chápete, že hodnota Bitcoinu může být extrémně volatilní a že jeho směnný kurz vůči jiným kryptoměnám nebo fiat měnám může výrazně kolísat, což může vést k výraznému a náhlému snížení hodnoty Vašeho majetku.\n" +
  "Tímto berete na vědomí, že nesete výhradní odpovědnost za získání potřebných informací o daňových nebo podobných povinnostech, které vzniknou v souvislosti s jakýmikoliv uskutečněnými transakcemi, a za srážku, výběr, vykazování a odvádění správných částek daně příslušným orgánům." +
  "Berete na vědomí, že v těchto Smluvních podmínkách nejsou uvedena všechna rizika související s užíváním kryptoměn.\n" +
  "### Důležité upozornění: Vexl pro pohodlí uživatelů zobrazuje aktuální cenu Bitcoinu. Nicméně žádná všeobecně uznávaná cena Bitcoinu neexistuje a ceny se na různých kryptoměnových burzách obvykle liší. Vexl tedy ukazuje průměrnou cenu Bitcoinu poskytovanou platformou CoinGecko ([https://coingecko.com](https://coingecko.com)).\n" +
  "## 14. UKONČENÍ\n" +
  'Vždy nás bude mrzet, že odcházíte, ale pokud se rozhodnete Vexl dále nevyužívat, budeme Vaše rozhodnutí respektovat. Váš uživatelský účet lze smazat poměrně snadno, a to klepnutím na tlačítko "odhlásit" umístěné v uživatelském rozhraní. Po odhlášení již nelze obnovit žádná data související s původním uživatelským účtem.\n' +
  "### Důležité upozornění: Pokud se rozhodnete odhlásit, buďte opatrní, protože odhlášením dojde k faktickému vymazání Vašeho uživatelského účtu. Taková akce je nevratná, takže pokud se v budoucnu rozhodnete Vexl znovu používat, nebudete moci obnovit žádná data spojená s Vaším původním uživatelským účtem a budete muset projít stejným procesem registrace jako jakýkoliv nový uživatel.\n" +
  "Vyhrazujeme si také výslovně právo pozastavit nebo trvale odepřít přístup k Vexlu uživatelům nacházejícím se v určitých zemích nebo státním příslušníkům určitých zemí, a to především z regulatorních důvodů (Vaši polohu nebo státní příslušnost můžeme identifikovat také nepřímo, například podle kódu země, appstoru nebo Vašeho telefonního čísla).\n" +
  "A konečně, vyhrazujeme si také právo zcela ukončit činnost Vexlu. V takovém případě Vás upozorníme alespoň třicet (30) dní předem. Po uplynutí této lhůty budeme mít možnost ukončit provoz Vexlu a vy tak již nebudete mít možnost přístupu ke svému uživatelskému účtu.\n" +
  "## 15. OZNÁMENÍ\n" +
  "### Vaše zprávy nám:\n" +
  "Můžete nás kontaktovat elektronicky prostřednictvím nástrojů dostupných na našich webových stránkách nebo prostřednictvím e-mailové adresy [support@vexl.it](mailto:support@vexl.it). Vaše zpráva je považována za doručenou, okamžikem, kdy Vám potvrdíme její doručení, což se vždy snažíme udělat okamžitě.\n" +
  "### Naše zprávy Vám:\n" +
  "Nechceme Vás příliš obtěžovat, ale občas Vás možná i tak budeme muset kontaktovat. V takovém případě použijeme push notifikaci, která se Vám zobrazí po přihlášení k Vašemu uživatelskému účtu.\n" +
  "## 16. ROZHODNÉ PRÁVO \n" +
  "Vaše užívání Vexlu, jakož i tyto Smluvní podmínky a veškeré související záležitosti, včetně sporů mezi Vámi a námi, se řídí právním řádem České republiky, a to bez ohledu na kolizní pravidla.\n\n" +
  "**Pouze pro spotřebitele:** Jsme povinni Vás informovat, že tato doložka o volbě práva Vás nezbavuje, pokud jste spotřebitel, práv vyplývajících z kogentních ustanovení práva země Vašeho obvyklého bydliště v případě, že by se toto právo jinak použilo podle čl. 6 odst. 1 nařízení Evropského parlamentu a Rady (ES) č. 593/2008 ze dne 17. června 2008 o právu rozhodném pro smluvní závazkové vztahy \n" +
  "(Řím I).\n" +
  "## 17. ŘEŠENÍ SPORŮ\n" +
  "Vždy se snažíme vyřešit jakýkoliv problém smírně a žádáme Vás o totéž. Proto souhlasíte s tím, že nás budete informovat o všech sporech, které vzniknou na základě těchto Smluvních podmínek, nebo v souvislosti s nimi, a souhlasíte s tím, že než se obrátíte na soud, pokusíte se vždy o mimosoudní řešení sporu.\n" +
  "Někdy však mimosoudní řešení sporu není prostě možné. V takovém případě budou veškeré spory, které se jakýmkoliv způsobem týkají těchto Smluvních podmínek, s konečnou platností řešeny před soudem České republiky příslušným podle místa sídla naší společnosti.\n\n" +
  "**Pouze pro spotřebitele:** Jsme povinni Vás informovat, že v případě jakéhokoliv sporu máte právo se obrátit ohledně možnosti mimosoudního řešení sporu na Český telekomunikační úřad, se sídlem Sokolovská 58/219, Praha 9, IČO: 701 06 975, prostřednictvím webové stránky [https://www.ctu.eu/out-court-dispute-resolution](https://www.ctu.eu/out-court-dispute-resolution), pro spory týkající se elektronických komunikací, a dále na Českou obchodní inspekci, se sídlem Štěpánská 567/15, 120 00 Praha 2, IČO: 000 20 869, prostřednictvím webové stránky [https://adr.coi.cz/cs](https://adr.coi.cz/cs), v případě jakýchkoliv jiných sporů. Můžete také využít platformu pro mimosoudní řešení sporů, umístěnou na webových stránkách [http://ec.europa.eu/consumer/odr](http://ec.europa.eu/consumer/odr).\n" +
  "## 18. ZMĚNY\n" +
  "**Provozovatel:** Souhlasíte s jakoukoliv případnou budoucí změnou provozovatele Vexl podle těchto Smluvních podmínek (postoupení smlouvy založené těmito Smluvními podmínkami). V případě takové změny Vás budeme vždy informovat.\n\n" +
  "**Smluvní podmínky:** Tyto Smluvní podmínky nebo další podmínky, které se vztahují na Vexl (například Zásady ochrany osobních údajů), můžeme čas od času změnit nebo doplnit a pokud tak učiníme, budeme Vás muset požádat, abyste si je znovu přečetli a souhlasili s nimi. Uvědomujeme si, že je to pro Vás nepohodlné, a proto slibujeme, že to nebudeme dělat příliš často. Vaše další užívání Vexlu potvrzuje Váš souhlas s aktualizovanými Smluvními podmínkami.\n"
