import {
  HANDSHAKE_INACTIVITY_TIMEOUT_MS,
  HUMAN_CODE_CONFIRMATION_TIMEOUT_MS,
  MAX_CONNECTED_MIGRATION_DURATION_MS,
  MAX_CONTROL_FRAME_PLAINTEXT_BYTES,
  MAX_DATA_CHUNK_PLAINTEXT_BYTES,
  MAX_FILE_BYTES,
  MAX_FILE_COUNT,
  MAX_FILE_RELATIVE_PATH_UTF8_BYTES,
  MAX_HANDSHAKE_MESSAGE_BYTES,
  MAX_MMKV_ENTRY_COUNT,
  MAX_MMKV_KEY_UTF8_BYTES,
  MAX_MMKV_VALUE_BYTES,
  MAX_QR_PAYLOAD_BYTES,
  MAX_TOTAL_SNAPSHOT_BYTES,
  QR_CODE_EXPIRY_MS,
  STREAM_INACTIVITY_TIMEOUT_MS,
  TIME_TO_INITIATE_AFTER_SCAN_MS,
} from './limits'

describe('transport limits match the specification exactly', () => {
  it('size limits', () => {
    expect(MAX_QR_PAYLOAD_BYTES).toBe(2048)
    expect(MAX_HANDSHAKE_MESSAGE_BYTES).toBe(65536)
    expect(MAX_CONTROL_FRAME_PLAINTEXT_BYTES).toBe(65536)
    expect(MAX_DATA_CHUNK_PLAINTEXT_BYTES).toBe(65536)
    expect(MAX_MMKV_KEY_UTF8_BYTES).toBe(256)
    expect(MAX_MMKV_ENTRY_COUNT).toBe(4096)
    expect(MAX_MMKV_VALUE_BYTES).toBe(67108864)
    expect(MAX_FILE_RELATIVE_PATH_UTF8_BYTES).toBe(512)
    expect(MAX_FILE_COUNT).toBe(4096)
    expect(MAX_FILE_BYTES).toBe(26214400)
    expect(MAX_TOTAL_SNAPSHOT_BYTES).toBe(1073741824)
  })

  it('timeouts', () => {
    expect(HANDSHAKE_INACTIVITY_TIMEOUT_MS).toBe(15000)
    expect(HUMAN_CODE_CONFIRMATION_TIMEOUT_MS).toBe(300000)
    expect(STREAM_INACTIVITY_TIMEOUT_MS).toBe(30000)
    expect(TIME_TO_INITIATE_AFTER_SCAN_MS).toBe(300000)
    expect(MAX_CONNECTED_MIGRATION_DURATION_MS).toBe(900000)
    expect(QR_CODE_EXPIRY_MS).toBe(300000)
  })
})
