import {Array, HashMap, Order, pipe, type Option} from 'effect'

export interface CountryInterface {
  name: string
  flag: string
  code: string
  dialCode: string
  colors: string[]
}

export const countries = [
  {
    'name': 'Afghanistan',
    'flag': '🇦🇫',
    'code': 'AF',
    'dialCode': '+93',
    'colors': ['#000000', '#00A859', '#FFDD00', '#FFFFFF'],
  },
  {
    'name': 'Åland Islands',
    'flag': '🇦🇽',
    'code': 'AX',
    'dialCode': '+358',
    'colors': ['#0053A5', '#FFD500', '#FF0000'],
  },
  {
    'name': 'Albania',
    'flag': '🇦🇱',
    'code': 'AL',
    'dialCode': '+355',
    'colors': ['#E41B13', '#000000'],
  },
  {
    'name': 'Algeria',
    'flag': '🇩🇿',
    'code': 'DZ',
    'dialCode': '+213',
    'colors': ['#006233', '#FFFFFF', '#D52B1E'],
  },
  {
    'name': 'American Samoa',
    'flag': '🇦🇸',
    'code': 'AS',
    'dialCode': '+1684',
    'colors': ['#041E42', '#FFFFFF', '#FFB81C'],
  },
  {
    'name': 'Andorra',
    'flag': '🇦🇩',
    'code': 'AD',
    'dialCode': '+376',
    'colors': ['#D52B1E', '#FFCE00', '#0033A0'],
  },
  {
    'name': 'Angola',
    'flag': '🇦🇴',
    'code': 'AO',
    'dialCode': '+244',
    'colors': ['#DD0000', '#000000', '#FFD700'],
  },
  {
    'name': 'Anguilla',
    'flag': '🇦🇮',
    'code': 'AI',
    'dialCode': '+1264',
    'colors': ['#00247D', '#FFFFFF', '#CF142B', '#FFB612'],
  },
  {
    'name': 'Antarctica',
    'flag': '🇦🇶',
    'code': 'AQ',
    'dialCode': '+672',
    'colors': ['#FFFFFF', '#002FA7'],
  },
  {
    'name': 'Antigua and Barbuda',
    'flag': '🇦🇬',
    'code': 'AG',
    'dialCode': '+1268',
    'colors': ['#000000', '#CE1126', '#FFD100', '#0072C6', '#FFFFFF'],
  },
  {
    'name': 'Argentina',
    'flag': '🇦🇷',
    'code': 'AR',
    'dialCode': '+54',
    'colors': ['#74ACDF', '#FFFFFF', '#F7E219'],
  },
  {
    'name': 'Armenia',
    'flag': '🇦🇲',
    'code': 'AM',
    'dialCode': '+374',
    'colors': ['#D90012', '#0033A0', '#F2A800'],
  },
  {
    'name': 'Aruba',
    'flag': '🇦🇼',
    'code': 'AW',
    'dialCode': '+297',
    'colors': ['#009CDE', '#F2A800', '#CE1126', '#FFFFFF'],
  },
  {
    'name': 'Australia',
    'flag': '🇦🇺',
    'code': 'AU',
    'dialCode': '+61',
    'colors': ['#00008B', '#FFFFFF', '#FF0000'],
  },
  {
    'name': 'Austria',
    'flag': '🇦🇹',
    'code': 'AT',
    'dialCode': '+43',
    'colors': ['#ED2939', '#FFFFFF'],
  },
  {
    'name': 'Azerbaijan',
    'flag': '🇦🇿',
    'code': 'AZ',
    'dialCode': '+994',
    'colors': ['#00B4E3', '#ED2939', '#FFFFFF', '#00A651'],
  },
  {
    'name': 'Bahamas',
    'flag': '🇧🇸',
    'code': 'BS',
    'dialCode': '+1242',
    'colors': ['#00ABCA', '#FFFFFF', '#FFD100', '#000000'],
  },
  {
    'name': 'Bahrain',
    'flag': '🇧🇭',
    'code': 'BH',
    'dialCode': '+973',
    'colors': ['#CE1126', '#FFFFFF'],
  },
  {
    'name': 'Bangladesh',
    'flag': '🇧🇩',
    'code': 'BD',
    'dialCode': '+880',
    'colors': ['#006A4E', '#F42A41'],
  },
  {
    'name': 'Barbados',
    'flag': '🇧🇧',
    'code': 'BB',
    'dialCode': '+1246',
    'colors': ['#00267F', '#FFC726', '#000000'],
  },
  {
    'name': 'Belarus',
    'flag': '🇧🇾',
    'code': 'BY',
    'dialCode': '+375',
    'colors': ['#D52B1E', '#009639', '#FFFFFF'],
  },
  {
    'name': 'Belgium',
    'flag': '🇧🇪',
    'code': 'BE',
    'dialCode': '+32',
    'colors': ['#000000', '#FFD700', '#FF0000'],
  },
  {
    'name': 'Belize',
    'flag': '🇧🇿',
    'code': 'BZ',
    'dialCode': '+501',
    'colors': ['#0033A0', '#FFFFFF', '#CE1126', '#6DA544'],
  },
  {
    'name': 'Benin',
    'flag': '🇧🇯',
    'code': 'BJ',
    'dialCode': '+229',
    'colors': ['#FCD116', '#008751', '#E8112D'],
  },
  {
    'name': 'Bermuda',
    'flag': '🇧🇲',
    'code': 'BM',
    'dialCode': '+1441',
    'colors': ['#FF0000', '#FFFFFF', '#0033A0', '#000000'],
  },
  {
    'name': 'Bhutan',
    'flag': '🇧🇹',
    'code': 'BT',
    'dialCode': '+975',
    'colors': ['#FFCC00', '#FF6600', '#FFFFFF'],
  },
  {
    'name': 'Bolivia, Plurinational State of Bolivia',
    'flag': '🇧🇴',
    'code': 'BO',
    'dialCode': '+591',
    'colors': ['#D52B1E', '#FFD700', '#007A33'],
  },
  {
    'name': 'Bosnia and Herzegovina',
    'flag': '🇧🇦',
    'code': 'BA',
    'dialCode': '+387',
    'colors': ['#002395', '#FFD100', '#FFFFFF'],
  },
  {
    'name': 'Botswana',
    'flag': '🇧🇼',
    'code': 'BW',
    'dialCode': '+267',
    'colors': ['#00BFFF', '#000000', '#FFFFFF'],
  },
  {
    'name': 'Bouvet Island',
    'flag': '🇧🇻',
    'code': 'BV',
    'dialCode': '+47',
    'colors': ['#BA0C2F', '#00205B', '#FFFFFF'],
  },
  {
    'name': 'Brazil',
    'flag': '🇧🇷',
    'code': 'BR',
    'dialCode': '+55',
    'colors': ['#009739', '#FFCC29', '#002776', '#FFFFFF'],
  },
  {
    'name': 'British Indian Ocean Territory',
    'flag': '🇮🇴',
    'code': 'IO',
    'dialCode': '+246',
    'colors': ['#012169', '#FFFFFF', '#FF0000', '#1A2F5D'],
  },
  {
    'name': 'Brunei Darussalam',
    'flag': '🇧🇳',
    'code': 'BN',
    'dialCode': '+673',
    'colors': ['#FFD100', '#FFFFFF', '#000000', '#C8102E'],
  },
  {
    'name': 'Bulgaria',
    'flag': '🇧🇬',
    'code': 'BG',
    'dialCode': '+359',
    'colors': ['#FFFFFF', '#00966E', '#D62612'],
  },
  {
    'name': 'Burkina Faso',
    'flag': '🇧🇫',
    'code': 'BF',
    'dialCode': '+226',
    'colors': ['#EF3340', '#009739', '#FFD100'],
  },
  {
    'name': 'Burundi',
    'flag': '🇧🇮',
    'code': 'BI',
    'dialCode': '+257',
    'colors': ['#06A77D', '#D21034', '#FFFFFF'],
  },
  {
    'name': 'Cambodia',
    'flag': '🇰🇭',
    'code': 'KH',
    'dialCode': '+855',
    'colors': ['#032EA1', '#FFFFFF', '#ED2939'],
  },
  {
    'name': 'Cameroon',
    'flag': '🇨🇲',
    'code': 'CM',
    'dialCode': '+237',
    'colors': ['#007A5E', '#CE1126', '#FFD100'],
  },
  {
    'name': 'Canada',
    'flag': '🇨🇦',
    'code': 'CA',
    'dialCode': '+1',
    'colors': ['#FF0000', '#FFFFFF'],
  },
  {
    'name': 'Cape Verde',
    'flag': '🇨🇻',
    'code': 'CV',
    'dialCode': '+238',
    'colors': ['#0033A0', '#FFFFFF', '#EF3340', '#FFD100'],
  },
  {
    'name': 'Cayman Islands',
    'flag': '🇰🇾',
    'code': 'KY',
    'dialCode': '+345',
    'colors': ['#00247D', '#FFFFFF', '#CF142B', '#000000'],
  },
  {
    'name': 'Central African Republic',
    'flag': '🇨🇫',
    'code': 'CF',
    'dialCode': '+236',
    'colors': ['#003082', '#FFFFFF', '#FFCD00', '#008751', '#EF3340'],
  },
  {
    'name': 'Chad',
    'flag': '🇹🇩',
    'code': 'TD',
    'dialCode': '+235',
    'colors': ['#002664', '#FECB00', '#C8102E'],
  },
  {
    'name': 'Chile',
    'flag': '🇨🇱',
    'code': 'CL',
    'dialCode': '+56',
    'colors': ['#0033A0', '#FFFFFF', '#D52B1E'],
  },
  {
    'name': 'China',
    'flag': '🇨🇳',
    'code': 'CN',
    'dialCode': '+86',
    'colors': ['#FFDE00', '#DE2910'],
  },
  {
    'name': 'Christmas Island',
    'flag': '🇨🇽',
    'code': 'CX',
    'dialCode': '+61',
    'colors': ['#007C3A', '#FFFFFF', '#00247D', '#FFD100'],
  },
  {
    'name': 'Cocos (Keeling) Islands',
    'flag': '🇨🇨',
    'code': 'CC',
    'dialCode': '+61',
    'colors': ['#0033A0', '#FFFFFF', '#CE1126', '#FFD100'],
  },
  {
    'name': 'Colombia',
    'flag': '🇨🇴',
    'code': 'CO',
    'dialCode': '+57',
    'colors': ['#FCD116', '#003087', '#CE1126'],
  },
  {
    'name': 'Comoros',
    'flag': '🇰🇲',
    'code': 'KM',
    'dialCode': '+269',
    'colors': ['#3A75C4', '#FFD100', '#EF3340', '#009739', '#FFFFFF'],
  },
  {
    'name': 'Congo',
    'flag': '🇨🇬',
    'code': 'CG',
    'dialCode': '+242',
    'colors': ['#009739', '#FFD100', '#EF3340'],
  },
  {
    'name': 'Congo, The Democratic Republic of the Congo',
    'flag': '🇨🇩',
    'code': 'CD',
    'dialCode': '+243',
    'colors': ['#007FFF', '#FFD100', '#CE1126'],
  },
  {
    'name': 'Cook Islands',
    'flag': '🇨🇰',
    'code': 'CK',
    'dialCode': '+682',
    'colors': ['#00247D', '#FFFFFF', '#CF142B'],
  },
  {
    'name': 'Costa Rica',
    'flag': '🇨🇷',
    'code': 'CR',
    'dialCode': '+506',
    'colors': ['#002B7F', '#FFFFFF', '#CE1126'],
  },
  {
    'name': "Cote d'Ivoire",
    'flag': '🇨🇮',
    'code': 'CI',
    'dialCode': '+225',
    'colors': ['#FF7900', '#FFFFFF', '#009739'],
  },
  {
    'name': 'Croatia',
    'flag': '🇭🇷',
    'code': 'HR',
    'dialCode': '+385',
    'colors': ['#FF0000', '#FFFFFF', '#171796', '#1C38D2'],
  },
  {
    'name': 'Cuba',
    'flag': '🇨🇺',
    'code': 'CU',
    'dialCode': '+53',
    'colors': ['#002A8F', '#FFFFFF', '#D52B1E'],
  },
  {
    'name': 'Cyprus',
    'flag': '🇨🇾',
    'code': 'CY',
    'dialCode': '+357',
    'colors': ['#D57800', '#FFFFFF', '#007A33'],
  },
  {
    'name': 'Czech Republic',
    'flag': '🇨🇿',
    'code': 'CZ',
    'dialCode': '+420',
    'colors': ['#11457E', '#FFFFFF', '#D7141A'],
  },
  {
    'name': 'Denmark',
    'flag': '🇩🇰',
    'code': 'DK',
    'dialCode': '+45',
    'colors': ['#C60C30', '#FFFFFF'],
  },
  {
    'name': 'Djibouti',
    'flag': '🇩🇯',
    'code': 'DJ',
    'dialCode': '+253',
    'colors': ['#6AB2E7', '#12AD2B', '#FFFFFF', '#D52B1E'],
  },
  {
    'name': 'Dominica',
    'flag': '🇩🇲',
    'code': 'DM',
    'dialCode': '+1767',
    'colors': ['#006847', '#FFD100', '#EF3340', '#FFFFFF'],
  },
  {
    'name': 'Dominican Republic',
    'flag': '🇩🇴',
    'code': 'DO',
    'dialCode': '+1849',
    'colors': ['#00247D', '#FFFFFF', '#CF142B'],
  },
  {
    'name': 'Ecuador',
    'flag': '🇪🇨',
    'code': 'EC',
    'dialCode': '+593',
    'colors': ['#FFD100', '#0033A0', '#EF3340'],
  },
  {
    'name': 'Egypt',
    'flag': '🇪🇬',
    'code': 'EG',
    'dialCode': '+20',
    'colors': ['#CE1126', '#FFFFFF', '#000000', '#FFD700'],
  },
  {
    'name': 'El Salvador',
    'flag': '🇸🇻',
    'code': 'SV',
    'dialCode': '+503',
    'colors': ['#0047AB', '#FFFFFF'],
  },
  {
    'name': 'Equatorial Guinea',
    'flag': '🇬🇶',
    'code': 'GQ',
    'dialCode': '+240',
    'colors': ['#3E9A00', '#FFFFFF', '#D7141A', '#00ADEF'],
  },
  {
    'name': 'Eritrea',
    'flag': '🇪🇷',
    'code': 'ER',
    'dialCode': '+291',
    'colors': ['#418FDE', '#EF3340', '#FFFFFF', '#D4A017'],
  },
  {
    'name': 'Estonia',
    'flag': '🇪🇪',
    'code': 'EE',
    'dialCode': '+372',
    'colors': ['#4891D9', '#FFFFFF', '#000000'],
  },
  {
    'name': 'Ethiopia',
    'flag': '🇪🇹',
    'code': 'ET',
    'dialCode': '+251',
    'colors': ['#078930', '#F4E000', '#DA121A'],
  },
  {
    'name': 'Falkland Islands (Malvinas)',
    'flag': '🇫🇰',
    'code': 'FK',
    'dialCode': '+500',
    'colors': ['#00247D', '#FFFFFF', '#CF142B'],
  },
  {
    'name': 'Faroe Islands',
    'flag': '🇫🇴',
    'code': 'FO',
    'dialCode': '+298',
    'colors': ['#FFFFFF', '#0033A0', '#EF3340'],
  },
  {
    'name': 'Fiji',
    'flag': '🇫🇯',
    'code': 'FJ',
    'dialCode': '+679',
    'colors': ['#012169', '#FFFFFF', '#CE1126', '#6AB1E6'],
  },
  {
    'name': 'Finland',
    'flag': '🇫🇮',
    'code': 'FI',
    'dialCode': '+358',
    'colors': ['#003580', '#FFFFFF'],
  },
  {
    'name': 'France',
    'flag': '🇫🇷',
    'code': 'FR',
    'dialCode': '+33',
    'colors': ['#0055A4', '#FFFFFF', '#EF4135'],
  },
  {
    'name': 'French Guiana',
    'flag': '🇬🇫',
    'code': 'GF',
    'dialCode': '+594',
    'colors': ['#009739', '#FFD100', '#EF3340'],
  },
  {
    'name': 'French Polynesia',
    'flag': '🇵🇫',
    'code': 'PF',
    'dialCode': '+689',
    'colors': ['#CE1126', '#FFFFFF'],
  },
  {
    'name': 'French Southern Territories',
    'flag': '🇹🇫',
    'code': 'TF',
    'dialCode': '+262',
    'colors': ['#012169', '#FFFFFF', '#C60C30'],
  },
  {
    'name': 'Gabon',
    'flag': '🇬🇦',
    'code': 'GA',
    'dialCode': '+241',
    'colors': ['#00AB39', '#FFD100', '#009EE0'],
  },
  {
    'name': 'Gambia',
    'flag': '🇬🇲',
    'code': 'GM',
    'dialCode': '+220',
    'colors': ['#3A75C4', '#FFFFFF', '#EF3340', '#3A9D23'],
  },
  {
    'name': 'Georgia',
    'flag': '🇬🇪',
    'code': 'GE',
    'dialCode': '+995',
    'colors': ['#FFFFFF', '#E50000'],
  },
  {
    'name': 'Germany',
    'flag': '🇩🇪',
    'code': 'DE',
    'dialCode': '+49',
    'colors': ['#000000', '#DD0000', '#FFCE00'],
  },
  {
    'name': 'Ghana',
    'flag': '🇬🇭',
    'code': 'GH',
    'dialCode': '+233',
    'colors': ['#006B3F', '#FCD116', '#CE1126', '#000000'],
  },
  {
    'name': 'Gibraltar',
    'flag': '🇬🇮',
    'code': 'GI',
    'dialCode': '+350',
    'colors': ['#FFFFFF', '#CF142B'],
  },
  {
    'name': 'Greece',
    'flag': '🇬🇷',
    'code': 'GR',
    'dialCode': '+30',
    'colors': ['#0D5EAF', '#FFFFFF'],
  },
  {
    'name': 'Greenland',
    'flag': '🇬🇱',
    'code': 'GL',
    'dialCode': '+299',
    'colors': ['#FFFFFF', '#EB1C2D'],
  },
  {
    'name': 'Grenada',
    'flag': '🇬🇩',
    'code': 'GD',
    'dialCode': '+1473',
    'colors': ['#FFCC00', '#007A5E', '#CE1126'],
  },
  {
    'name': 'Guadeloupe',
    'flag': '🇬🇵',
    'code': 'GP',
    'dialCode': '+590',
    'colors': ['#F2A800', '#0033A0', '#006600'],
  },
  {
    'name': 'Guam',
    'flag': '🇬🇺',
    'code': 'GU',
    'dialCode': '+1671',
    'colors': ['#002147', '#FFFFFF', '#EF3340'],
  },
  {
    'name': 'Guatemala',
    'flag': '🇬🇹',
    'code': 'GT',
    'dialCode': '+502',
    'colors': ['#4997D0', '#FFFFFF', '#FFD100', '#006847'],
  },
  {
    'name': 'Guinea',
    'flag': '🇬🇳',
    'code': 'GN',
    'dialCode': '+224',
    'colors': ['#CE1126', '#FCD116', '#009460'],
  },
  {
    'name': 'Guinea-Bissau',
    'flag': '🇬🇼',
    'code': 'GW',
    'dialCode': '+245',
    'colors': ['#CE1126', '#FFD100', '#009739', '#000000'],
  },
  {
    'name': 'Guyana',
    'flag': '🇬🇾',
    'code': 'GY',
    'dialCode': '+592',
    'colors': ['#009739', '#FFD100', '#EF3340', '#FFFFFF', '#000000'],
  },
  {
    'name': 'Haiti',
    'flag': '🇭🇹',
    'code': 'HT',
    'dialCode': '+509',
    'colors': ['#00209F', '#D21034', '#FFFFFF', '#008000'],
  },
  {
    'name': 'Heard Island and Mcdonald Islands',
    'flag': '🇭🇲',
    'code': 'HM',
    'dialCode': '+672',
    'colors': ['#00008B', '#FFFFFF', '#FF0000'],
  },
  {
    'name': 'Holy See (Vatican City State)',
    'flag': '🇻🇦',
    'code': 'VA',
    'dialCode': '+379',
    'colors': ['#FFFFFF', '#FFCC00'],
  },
  {
    'name': 'Honduras',
    'flag': '🇭🇳',
    'code': 'HN',
    'dialCode': '+504',
    'colors': ['#0073CF', '#FFFFFF'],
  },
  {
    'name': 'Hong Kong',
    'flag': '🇭🇰',
    'code': 'HK',
    'dialCode': '+852',
    'colors': ['#DE2910', '#FFFFFF'],
  },
  {
    'name': 'Hungary',
    'flag': '🇭🇺',
    'code': 'HU',
    'dialCode': '+36',
    'colors': ['#C8102E', '#FFFFFF', '#007A33'],
  },
  {
    'name': 'Iceland',
    'flag': '🇮🇸',
    'code': 'IS',
    'dialCode': '+354',
    'colors': ['#003897', '#FFFFFF', '#DC1E35'],
  },
  {
    'name': 'India',
    'flag': '🇮🇳',
    'code': 'IN',
    'dialCode': '+91',
    'colors': ['#FF9933', '#FFFFFF', '#138808', '#000080'],
  },
  {
    'name': 'Indonesia',
    'flag': '🇮🇩',
    'code': 'ID',
    'dialCode': '+62',
    'colors': ['#CE1126', '#FFFFFF'],
  },
  {
    'name': 'Iran, Islamic Republic of Persian Gulf',
    'flag': '🇮🇷',
    'code': 'IR',
    'dialCode': '+98',
    'colors': ['#DA0000', '#FFFFFF', '#239F40'],
  },
  {
    'name': 'Iraq',
    'flag': '🇮🇶',
    'code': 'IQ',
    'dialCode': '+964',
    'colors': ['#CE1126', '#FFFFFF', '#007A3D', '#000000'],
  },
  {
    'name': 'Ireland',
    'flag': '🇮🇪',
    'code': 'IE',
    'dialCode': '+353',
    'colors': ['#009A49', '#FFFFFF', '#FF7900'],
  },
  {
    'name': 'Israel',
    'flag': '🇮🇱',
    'code': 'IL',
    'dialCode': '+972',
    'colors': ['#0038B8', '#FFFFFF'],
  },
  {
    'name': 'Italy',
    'flag': '🇮🇹',
    'code': 'IT',
    'dialCode': '+39',
    'colors': ['#008C45', '#FFFFFF', '#CD212A'],
  },
  {
    'name': 'Jamaica',
    'flag': '🇯🇲',
    'code': 'JM',
    'dialCode': '+1876',
    'colors': ['#FED100', '#000000', '#007847'],
  },
  {
    'name': 'Japan',
    'flag': '🇯🇵',
    'code': 'JP',
    'dialCode': '+81',
    'colors': ['#FFFFFF', '#BC002D'],
  },
  {
    'name': 'Jordan',
    'flag': '🇯🇴',
    'code': 'JO',
    'dialCode': '+962',
    'colors': ['#000000', '#FFFFFF', '#CE1126', '#007A3D'],
  },
  {
    'name': 'Kazakhstan',
    'flag': '🇰🇿',
    'code': 'KZ',
    'dialCode': '+7',
    'colors': ['#00AFCA', '#FFD700'],
  },
  {
    'name': 'Kenya',
    'flag': '🇰🇪',
    'code': 'KE',
    'dialCode': '+254',
    'colors': ['#006600', '#FFFFFF', '#BB0000', '#000000'],
  },
  {
    'name': 'Kiribati',
    'flag': '🇰🇮',
    'code': 'KI',
    'dialCode': '+686',
    'colors': ['#0033A0', '#FFFFFF', '#FFCC00', '#CE1126'],
  },
  {
    'name': "Korea, Democratic People's Republic of Korea",
    'flag': '🇰🇵',
    'code': 'KP',
    'dialCode': '+850',
    'colors': ['#0047AB', '#FFFFFF', '#EF1C27'],
  },
  {
    'name': 'Korea, Republic of South Korea',
    'flag': '🇰🇷',
    'code': 'KR',
    'dialCode': '+82',
    'colors': ['#FFFFFF', '#003478', '#C60C30', '#CDBE10'],
  },
  {
    'name': 'Kosovo',
    'flag': '🇽🇰',
    'code': 'XK',
    'dialCode': '+383',
    'colors': ['#00247D', '#FFFFFF', '#D0A643'],
  },
  {
    'name': 'Kuwait',
    'flag': '🇰🇼',
    'code': 'KW',
    'dialCode': '+965',
    'colors': ['#007A3D', '#FFFFFF', '#CE1126', '#000000'],
  },
  {
    'name': 'Kyrgyzstan',
    'flag': '🇰🇬',
    'code': 'KG',
    'dialCode': '+996',
    'colors': ['#CE1126', '#FFCC00'],
  },
  {
    'name': 'Laos',
    'flag': '🇱🇦',
    'code': 'LA',
    'dialCode': '+856',
    'colors': ['#CE1126', '#002868', '#FFFFFF'],
  },
  {
    'name': 'Latvia',
    'flag': '🇱🇻',
    'code': 'LV',
    'dialCode': '+371',
    'colors': ['#9E3039', '#FFFFFF'],
  },
  {
    'name': 'Lebanon',
    'flag': '🇱🇧',
    'code': 'LB',
    'dialCode': '+961',
    'colors': ['#FF0000', '#FFFFFF', '#00A651'],
  },
  {
    'name': 'Lesotho',
    'flag': '🇱🇸',
    'code': 'LS',
    'dialCode': '+266',
    'colors': ['#000000', '#FFFFFF', '#009739', '#0033A0'],
  },
  {
    'name': 'Liberia',
    'flag': '🇱🇷',
    'code': 'LR',
    'dialCode': '+231',
    'colors': ['#C60C30', '#FFFFFF', '#002868'],
  },
  {
    'name': 'Libyan Arab Jamahiriya',
    'flag': '🇱🇾',
    'code': 'LY',
    'dialCode': '+218',
    'colors': ['#239F40', '#FFFFFF', '#CE1126', '#000000'],
  },
  {
    'name': 'Liechtenstein',
    'flag': '🇱🇮',
    'code': 'LI',
    'dialCode': '+423',
    'colors': ['#002679', '#F7D116'],
  },
  {
    'name': 'Lithuania',
    'flag': '🇱🇹',
    'code': 'LT',
    'dialCode': '+370',
    'colors': ['#FDB913', '#007A3D', '#C60C30'],
  },
  {
    'name': 'Luxembourg',
    'flag': '🇱🇺',
    'code': 'LU',
    'dialCode': '+352',
    'colors': ['#00A1DE', '#FFFFFF', '#EF3340'],
  },
  {
    'name': 'Macao',
    'flag': '🇲🇴',
    'code': 'MO',
    'dialCode': '+853',
    'colors': ['#00785E', '#FFFFFF', '#FFD700'],
  },
  {
    'name': 'Macedonia',
    'flag': '🇲🇰',
    'code': 'MK',
    'dialCode': '+389',
    'colors': ['#D20000', '#FFD700'],
  },
  {
    'name': 'Madagascar',
    'flag': '🇲🇬',
    'code': 'MG',
    'dialCode': '+261',
    'colors': ['#009739', '#FFFFFF', '#CE1126'],
  },
  {
    'name': 'Malawi',
    'flag': '🇲🇼',
    'code': 'MW',
    'dialCode': '+265',
    'colors': ['#D52B1E', '#FFFFFF', '#007847', '#000000'],
  },
  {
    'name': 'Malaysia',
    'flag': '🇲🇾',
    'code': 'MY',
    'dialCode': '+60',
    'colors': ['#010066', '#FFFFFF', '#FED100', '#DC0000'],
  },
  {
    'name': 'Maldives',
    'flag': '🇲🇻',
    'code': 'MV',
    'dialCode': '+960',
    'colors': ['#D21034', '#FFFFFF', '#007C59'],
  },
  {
    'name': 'Mali',
    'flag': '🇲🇱',
    'code': 'ML',
    'dialCode': '+223',
    'colors': ['#14B53A', '#FFD100', '#CE1126'],
  },
  {
    'name': 'Malta',
    'flag': '🇲🇹',
    'code': 'MT',
    'dialCode': '+356',
    'colors': ['#FFFFFF', '#EF3340'],
  },
  {
    'name': 'Marshall Islands',
    'flag': '🇲🇭',
    'code': 'MH',
    'dialCode': '+692',
    'colors': ['#0033A0', '#FFFFFF', '#FF8200'],
  },
  {
    'name': 'Martinique',
    'flag': '🇲🇶',
    'code': 'MQ',
    'dialCode': '+596',
    'colors': ['#001489', '#FFFFFF'],
  },
  {
    'name': 'Mauritania',
    'flag': '🇲🇷',
    'code': 'MR',
    'dialCode': '+222',
    'colors': ['#007A5E', '#FFD700'],
  },
  {
    'name': 'Mauritius',
    'flag': '🇲🇺',
    'code': 'MU',
    'dialCode': '+230',
    'colors': ['#1A206D', '#FFD100', '#009739', '#EE2737'],
  },
  {
    'name': 'Mayotte',
    'flag': '🇾🇹',
    'code': 'YT',
    'dialCode': '+262',
    'colors': ['#FFFFFF', '#D52B1E'],
  },
  {
    'name': 'Mexico',
    'flag': '🇲🇽',
    'code': 'MX',
    'dialCode': '+52',
    'colors': ['#006847', '#FFFFFF', '#CE1126'],
  },
  {
    'name': 'Micronesia, Federated States of Micronesia',
    'flag': '🇫🇲',
    'code': 'FM',
    'dialCode': '+691',
    'colors': ['#75B2DD', '#FFFFFF'],
  },
  {
    'name': 'Moldova',
    'flag': '🇲🇩',
    'code': 'MD',
    'dialCode': '+373',
    'colors': ['#0033A0', '#FFD100', '#CE1126'],
  },
  {
    'name': 'Monaco',
    'flag': '🇲🇨',
    'code': 'MC',
    'dialCode': '+377',
    'colors': ['#CE1126', '#FFFFFF'],
  },
  {
    'name': 'Mongolia',
    'flag': '🇲🇳',
    'code': 'MN',
    'dialCode': '+976',
    'colors': ['#C4272F', '#0033A0', '#FFD700'],
  },
  {
    'name': 'Montenegro',
    'flag': '🇲🇪',
    'code': 'ME',
    'dialCode': '+382',
    'colors': ['#C40305', '#FFD700'],
  },
  {
    'name': 'Montserrat',
    'flag': '🇲🇸',
    'code': 'MS',
    'dialCode': '+1664',
    'colors': ['#00247D', '#FFFFFF', '#CF142B'],
  },
  {
    'name': 'Morocco',
    'flag': '🇲🇦',
    'code': 'MA',
    'dialCode': '+212',
    'colors': ['#C1272D', '#006233'],
  },
  {
    'name': 'Mozambique',
    'flag': '🇲🇿',
    'code': 'MZ',
    'dialCode': '+258',
    'colors': ['#FF0000', '#006B3F', '#FFD100', '#000000'],
  },
  {
    'name': 'Myanmar',
    'flag': '🇲🇲',
    'code': 'MM',
    'dialCode': '+95',
    'colors': ['#FFD600', '#EF4135', '#43B02A', '#FFFFFF'],
  },
  {
    'name': 'Namibia',
    'flag': '🇳🇦',
    'code': 'NA',
    'dialCode': '+264',
    'colors': ['#0033A0', '#D21034', '#FFD100', '#3A5EAB'],
  },
  {
    'name': 'Nauru',
    'flag': '🇳🇷',
    'code': 'NR',
    'dialCode': '+674',
    'colors': ['#002B7F', '#FFC72C', '#FFFFFF'],
  },
  {
    'name': 'Nepal',
    'flag': '🇳🇵',
    'code': 'NP',
    'dialCode': '+977',
    'colors': ['#DC143C', '#003893', '#FFFFFF'],
  },
  {
    'name': 'Netherlands',
    'flag': '🇳🇱',
    'code': 'NL',
    'dialCode': '+31',
    'colors': ['#21468B', '#FFFFFF', '#AE1C28'],
  },
  {
    'name': 'Netherlands Antilles',
    'flag': '',
    'code': 'AN',
    'dialCode': '+599',
    'colors': ['#002868', '#FFFFFF', '#CE1126'],
  },
  {
    'name': 'New Caledonia',
    'flag': '🇳🇨',
    'code': 'NC',
    'dialCode': '+687',
    'colors': ['#008751', '#FFD700', '#0000FF', '#FF0000'],
  },
  {
    'name': 'New Zealand',
    'flag': '🇳🇿',
    'code': 'NZ',
    'dialCode': '+64',
    'colors': ['#00247D', '#FFFFFF', '#FF0000'],
  },
  {
    'name': 'Nicaragua',
    'flag': '🇳🇮',
    'code': 'NI',
    'dialCode': '+505',
    'colors': ['#0067C5', '#FFFFFF'],
  },
  {
    'name': 'Niger',
    'flag': '🇳🇪',
    'code': 'NE',
    'dialCode': '+227',
    'colors': ['#E05206', '#FFFFFF', '#0DB02B'],
  },
  {
    'name': 'Nigeria',
    'flag': '🇳🇬',
    'code': 'NG',
    'dialCode': '+234',
    'colors': ['#008753', '#FFFFFF'],
  },
  {
    'name': 'Niue',
    'flag': '🇳🇺',
    'code': 'NU',
    'dialCode': '+683',
    'colors': ['#00247D', '#FFFFFF', '#CF142B', '#F7E60C'],
  },
  {
    'name': 'Norfolk Island',
    'flag': '🇳🇫',
    'code': 'NF',
    'dialCode': '+672',
    'colors': ['#007846', '#FFFFFF'],
  },
  {
    'name': 'Northern Mariana Islands',
    'flag': '🇲🇵',
    'code': 'MP',
    'dialCode': '+1670',
    'colors': ['#002868', '#FFFFFF', '#A0A0A0'],
  },
  {
    'name': 'Norway',
    'flag': '🇳🇴',
    'code': 'NO',
    'dialCode': '+47',
    'colors': ['#BA0C2F', '#00205B', '#FFFFFF'],
  },
  {
    'name': 'Oman',
    'flag': '🇴🇲',
    'code': 'OM',
    'dialCode': '+968',
    'colors': ['#D52B1E', '#FFFFFF', '#007A3D'],
  },
  {
    'name': 'Pakistan',
    'flag': '🇵🇰',
    'code': 'PK',
    'dialCode': '+92',
    'colors': ['#01411C', '#FFFFFF'],
  },
  {
    'name': 'Palastine',
    'flag': '🇵🇸',
    'code': 'PS',
    'dialCode': '+970',
    'colors': ['#000000', '#FFFFFF', '#007A3D', '#CE1126'],
  },
  {
    'name': 'Palau',
    'flag': '🇵🇼',
    'code': 'PW',
    'dialCode': '+680',
    'colors': ['#4AADD6', '#FFDE00'],
  },
  {
    'name': 'Panama',
    'flag': '🇵🇦',
    'code': 'PA',
    'dialCode': '+507',
    'colors': ['#005AA7', '#FFFFFF', '#EF3340'],
  },
  {
    'name': 'Papua New Guinea',
    'flag': '🇵🇬',
    'code': 'PG',
    'dialCode': '+675',
    'colors': ['#000000', '#FFFFFF', '#FFD100', '#D52B1E'],
  },
  {
    'name': 'Paraguay',
    'flag': '🇵🇾',
    'code': 'PY',
    'dialCode': '+595',
    'colors': ['#0033A0', '#FFFFFF', '#D52B1E'],
  },
  {
    'name': 'Peru',
    'flag': '🇵🇪',
    'code': 'PE',
    'dialCode': '+51',
    'colors': ['#D91023', '#FFFFFF'],
  },
  {
    'name': 'Philippines',
    'flag': '🇵🇭',
    'code': 'PH',
    'dialCode': '+63',
    'colors': ['#0038A8', '#CE1126', '#FFD700', '#FFFFFF'],
  },
  {
    'name': 'Pitcairn',
    'flag': '🇵🇳',
    'code': 'PN',
    'dialCode': '+64',
    'colors': ['#00247D', '#FFFFFF', '#CF142B', '#FFD100', '#006847'],
  },
  {
    'name': 'Poland',
    'flag': '🇵🇱',
    'code': 'PL',
    'dialCode': '+48',
    'colors': ['#D4213D', '#FFFFFF'],
  },
  {
    'name': 'Portugal',
    'flag': '🇵🇹',
    'code': 'PT',
    'dialCode': '+351',
    'colors': ['#00A550', '#FF0000', '#FFD100'],
  },
  {
    'name': 'Puerto Rico',
    'flag': '🇵🇷',
    'code': 'PR',
    'dialCode': '+1939',
    'colors': ['#3A75C4', '#FFFFFF', '#CE1126'],
  },
  {
    'name': 'Qatar',
    'flag': '🇶🇦',
    'code': 'QA',
    'dialCode': '+974',
    'colors': ['#8D1B3D', '#FFFFFF'],
  },
  {
    'name': 'Reunion',
    'flag': '🇷🇪',
    'code': 'RE',
    'dialCode': '+262',
    'colors': ['#0033A0', '#FFD100', '#CE1126'],
  },
  {
    'name': 'Romania',
    'flag': '🇷🇴',
    'code': 'RO',
    'dialCode': '+40',
    'colors': ['#002B7F', '#FCD116', '#CE1126'],
  },
  {
    'name': 'Russia',
    'flag': '🇷🇺',
    'code': 'RU',
    'dialCode': '+7',
    'colors': ['#0033A0', '#FFFFFF', '#D52B1E'],
  },
  {
    'name': 'Rwanda',
    'flag': '🇷🇼',
    'code': 'RW',
    'dialCode': '+250',
    'colors': ['#20603D', '#FAD201', '#00A1DE'],
  },
  {
    'name': 'Saint Barthelemy',
    'flag': '🇧🇱',
    'code': 'BL',
    'dialCode': '+590',
    'colors': ['#FFFFFF', '#FFD700', '#0033A0'],
  },
  {
    'name': 'Saint Helena, Ascension and Tristan Da Cunha',
    'flag': '🇸🇭',
    'code': 'SH',
    'dialCode': '+290',
    'colors': ['#012169', '#FFFFFF', '#C8102E'],
  },
  {
    'name': 'Saint Kitts and Nevis',
    'flag': '🇰🇳',
    'code': 'KN',
    'dialCode': '+1869',
    'colors': ['#007A5E', '#FFD100', '#EF3340', '#000000', '#FFFFFF'],
  },
  {
    'name': 'Saint Lucia',
    'flag': '🇱🇨',
    'code': 'LC',
    'dialCode': '+1758',
    'colors': ['#6CF', '#FFD100', '#000000', '#FFFFFF'],
  },
  {
    'name': 'Saint Martin',
    'flag': '🇲🇫',
    'code': 'MF',
    'dialCode': '+590',
    'colors': ['#00247D', '#CE1126', '#FFFFFF'],
  },
  {
    'name': 'Saint Pierre and Miquelon',
    'flag': '🇵🇲',
    'code': 'PM',
    'dialCode': '+508',
    'colors': ['#FDE910', '#00ADEF', '#EE2737'],
  },
  {
    'name': 'Saint Vincent and the Grenadines',
    'flag': '🇻🇨',
    'code': 'VC',
    'dialCode': '+1784',
    'colors': ['#FFD100', '#009739', '#0033A0'],
  },
  {
    'name': 'Samoa',
    'flag': '🇼🇸',
    'code': 'WS',
    'dialCode': '+685',
    'colors': ['#CE1126', '#002B7F', '#FFFFFF'],
  },
  {
    'name': 'San Marino',
    'flag': '🇸🇲',
    'code': 'SM',
    'dialCode': '+378',
    'colors': ['#5EB6E4', '#FFFFFF'],
  },
  {
    'name': 'Sao Tome and Principe',
    'flag': '🇸🇹',
    'code': 'ST',
    'dialCode': '+239',
    'colors': ['#12AD2B', '#FFD700', '#FF0000'],
  },
  {
    'name': 'Saudi Arabia',
    'flag': '🇸🇦',
    'code': 'SA',
    'dialCode': '+966',
    'colors': ['#006C35', '#FFFFFF'],
  },
  {
    'name': 'Senegal',
    'flag': '🇸🇳',
    'code': 'SN',
    'dialCode': '+221',
    'colors': ['#00853F', '#FFD100', '#E31B23'],
  },
  {
    'name': 'Serbia',
    'flag': '🇷🇸',
    'code': 'RS',
    'dialCode': '+381',
    'colors': ['#006CB7', '#FFFFFF', '#C6363C'],
  },
  {
    'name': 'Seychelles',
    'flag': '🇸🇨',
    'code': 'SC',
    'dialCode': '+248',
    'colors': ['#003D88', '#FFD100', '#007A3D', '#D62828', '#FFFFFF'],
  },
  {
    'name': 'Sierra Leone',
    'flag': '🇸🇱',
    'code': 'SL',
    'dialCode': '+232',
    'colors': ['#1EB53A', '#FFFFFF', '#0072C6'],
  },
  {
    'name': 'Singapore',
    'flag': '🇸🇬',
    'code': 'SG',
    'dialCode': '+65',
    'colors': ['#EF3340', '#FFFFFF'],
  },
  {
    'name': 'Slovakia',
    'flag': '🇸🇰',
    'code': 'SK',
    'dialCode': '+421',
    'colors': ['#0B4EA2', '#FFFFFF', '#EF3340'],
  },
  {
    'name': 'Slovenia',
    'flag': '🇸🇮',
    'code': 'SI',
    'dialCode': '+386',
    'colors': ['#0057A6', '#FFFFFF', '#EF3340'],
  },
  {
    'name': 'Solomon Islands',
    'flag': '🇸🇧',
    'code': 'SB',
    'dialCode': '+677',
    'colors': ['#007849', '#FFD100', '#0033A0', '#FFFFFF'],
  },
  {
    'name': 'Somalia',
    'flag': '🇸🇴',
    'code': 'SO',
    'dialCode': '+252',
    'colors': ['#4189DD', '#FFFFFF'],
  },
  {
    'name': 'South Africa',
    'flag': '🇿🇦',
    'code': 'ZA',
    'dialCode': '+27',
    'colors': [
      '#007A4D',
      '#000000',
      '#FFD100',
      '#E03C31',
      '#FFFFFF',
      '#002395',
    ],
  },
  {
    'name': 'South Georgia and the South Sandwich Islands',
    'flag': '🇬🇸',
    'code': 'GS',
    'dialCode': '+500',
    'colors': ['#00247D', '#FFFFFF', '#CF142B'],
  },
  {
    'name': 'South Sudan',
    'flag': '🇸🇸',
    'code': 'SS',
    'dialCode': '+211',
    'colors': ['#078930', '#FFD100', '#D21034', '#000000', '#0033A0'],
  },
  {
    'name': 'Spain',
    'flag': '🇪🇸',
    'code': 'ES',
    'dialCode': '+34',
    'colors': ['#AA151B', '#F1BF00'],
  },
  {
    'name': 'Sri Lanka',
    'flag': '🇱🇰',
    'code': 'LK',
    'dialCode': '+94',
    'colors': ['#FFB000', '#00564B', '#8D2029', '#FF6600', '#FFFFFF'],
  },
  {
    'name': 'Sudan',
    'flag': '🇸🇩',
    'code': 'SD',
    'dialCode': '+249',
    'colors': ['#008000', '#FFFFFF', '#D21034', '#000000'],
  },
  {
    'name': 'Suriname',
    'flag': '🇸🇷',
    'code': 'SR',
    'dialCode': '+597',
    'colors': ['#377E3F', '#FFFFFF', '#B40A2D', '#FFD100'],
  },
  {
    'name': 'Svalbard and Jan Mayen',
    'flag': '🇸🇯',
    'code': 'SJ',
    'dialCode': '+47',
    'colors': ['#BA0C2F', '#00205B', '#FFFFFF'],
  },
  {
    'name': 'Swaziland',
    'flag': '🇸🇿',
    'code': 'SZ',
    'dialCode': '+268',
    'colors': ['#003DA5', '#FFD100', '#EF3340', '#FFFFFF', '#000000'],
  },
  {
    'name': 'Sweden',
    'flag': '🇸🇪',
    'code': 'SE',
    'dialCode': '+46',
    'colors': ['#005BAC', '#FECB00'],
  },
  {
    'name': 'Switzerland',
    'flag': '🇨🇭',
    'code': 'CH',
    'dialCode': '+41',
    'colors': ['#D52B1E', '#FFFFFF'],
  },
  {
    'name': 'Syrian Arab Republic',
    'flag': '🇸🇾',
    'code': 'SY',
    'dialCode': '+963',
    'colors': ['#000000', '#FFFFFF', '#CE1126', '#007A3D'],
  },
  {
    'name': 'Taiwan',
    'flag': '🇹🇼',
    'code': 'TW',
    'dialCode': '+886',
    'colors': ['#FE0000', '#FFFFFF', '#000095'],
  },
  {
    'name': 'Tajikistan',
    'flag': '🇹🇯',
    'code': 'TJ',
    'dialCode': '+992',
    'colors': ['#006600', '#FFFFFF', '#D52B1E', '#FFD100'],
  },
  {
    'name': 'Tanzania, United Republic of Tanzania',
    'flag': '🇹🇿',
    'code': 'TZ',
    'dialCode': '+255',
    'colors': ['#00A859', '#3D4444', '#FFD100', '#0033A0'],
  },
  {
    'name': 'Thailand',
    'flag': '🇹🇭',
    'code': 'TH',
    'dialCode': '+66',
    'colors': ['#A51931', '#F4F5F8', '#2D2A4A'],
  },
  {
    'name': 'Timor-Leste',
    'flag': '🇹🇱',
    'code': 'TL',
    'dialCode': '+670',
    'colors': ['#FF0000', '#000000', '#FFD100', '#FFFFFF'],
  },
  {
    'name': 'Togo',
    'flag': '🇹🇬',
    'code': 'TG',
    'dialCode': '+228',
    'colors': ['#006B3F', '#FFD100', '#D21034', '#FFFFFF'],
  },
  {
    'name': 'Tokelau',
    'flag': '🇹🇰',
    'code': 'TK',
    'dialCode': '+690',
    'colors': ['#00247D', '#FFD100', '#FFFFFF'],
  },
  {
    'name': 'Tonga',
    'flag': '🇹🇴',
    'code': 'TO',
    'dialCode': '+676',
    'colors': ['#C10000', '#FFFFFF'],
  },
  {
    'name': 'Trinidad and Tobago',
    'flag': '🇹🇹',
    'code': 'TT',
    'dialCode': '+1868',
    'colors': ['#FF0000', '#FFFFFF', '#000000'],
  },
  {
    'name': 'Tunisia',
    'flag': '🇹🇳',
    'code': 'TN',
    'dialCode': '+216',
    'colors': ['#E70013', '#FFFFFF'],
  },
  {
    'name': 'Türkiye',
    'flag': '🇹🇷',
    'code': 'TR',
    'dialCode': '+90',
    'colors': ['#E30A17', '#FFFFFF'],
  },
  {
    'name': 'Turkmenistan',
    'flag': '🇹🇲',
    'code': 'TM',
    'dialCode': '+993',
    'colors': ['#00AF66', '#FFFFFF', '#FF0000', '#FFD700'],
  },
  {
    'name': 'Turks and Caicos Islands',
    'flag': '🇹🇨',
    'code': 'TC',
    'dialCode': '+1649',
    'colors': ['#00247D', '#FFFFFF', '#CF142B', '#F4C430'],
  },
  {
    'name': 'Tuvalu',
    'flag': '🇹🇻',
    'code': 'TV',
    'dialCode': '+688',
    'colors': ['#00247D', '#FFFFFF', '#CF142B', '#FFD100'],
  },
  {
    'name': 'Uganda',
    'flag': '🇺🇬',
    'code': 'UG',
    'dialCode': '+256',
    'colors': ['#FFD100', '#000000', '#D21034'],
  },
  {
    'name': 'Ukraine',
    'flag': '🇺🇦',
    'code': 'UA',
    'dialCode': '+380',
    'colors': ['#0057B7', '#FFD700'],
  },
  {
    'name': 'United Arab Emirates',
    'flag': '🇦🇪',
    'code': 'AE',
    'dialCode': '+971',
    'colors': ['#00732F', '#FFFFFF', '#EF3340', '#000000'],
  },
  {
    'name': 'United Kingdom',
    'flag': '🇬🇧',
    'code': 'GB',
    'dialCode': '+44',
    'colors': ['#00247D', '#FFFFFF', '#CF142B'],
  },
  {
    'name': 'United States',
    'flag': '🇺🇸',
    'code': 'US',
    'dialCode': '+1',
    'colors': ['#3C3B6E', '#FFFFFF', '#B22234'],
  },
  {
    'name': 'Uruguay',
    'flag': '🇺🇾',
    'code': 'UY',
    'dialCode': '+598',
    'colors': ['#0038A8', '#FFFFFF', '#FFD100'],
  },
  {
    'name': 'Uzbekistan',
    'flag': '🇺🇿',
    'code': 'UZ',
    'dialCode': '+998',
    'colors': ['#1EB53A', '#0099B5', '#CE1126', '#FFFFFF'],
  },
  {
    'name': 'Vanuatu',
    'flag': '🇻🇺',
    'code': 'VU',
    'dialCode': '+678',
    'colors': ['#000000', '#FFD100', '#007847', '#EF3340'],
  },
  {
    'name': 'Venezuela, Bolivarian Republic of Venezuela',
    'flag': '🇻🇪',
    'code': 'VE',
    'dialCode': '+58',
    'colors': ['#FCD116', '#003DA5', '#EF3340'],
  },
  {
    'name': 'Vietnam',
    'flag': '🇻🇳',
    'code': 'VN',
    'dialCode': '+84',
    'colors': ['#DA251D', '#FFFF00'],
  },
  {
    'name': 'Virgin Islands, British',
    'flag': '🇻🇬',
    'code': 'VG',
    'dialCode': '+1284',
    'colors': ['#00247D', '#FFFFFF', '#CF142B', '#006847', '#FFD100'],
  },
  {
    'name': 'Virgin Islands, U.S.',
    'flag': '🇻🇮',
    'code': 'VI',
    'dialCode': '+1340',
    'colors': ['#00247D', '#FFFFFF', '#CF142B', '#FFD100', '#007A33'],
  },
  {
    'name': 'Wallis and Futuna',
    'flag': '🇼🇫',
    'code': 'WF',
    'dialCode': '+681',
    'colors': ['#CE1126', '#FFFFFF', '#002395'],
  },
  {
    'name': 'Yemen',
    'flag': '🇾🇪',
    'code': 'YE',
    'dialCode': '+967',
    'colors': ['#CE1126', '#FFFFFF', '#000000'],
  },
  {
    'name': 'Zambia',
    'flag': '🇿🇲',
    'code': 'ZM',
    'dialCode': '+260',
    'colors': ['#198A00', '#FDDA24', '#EF3340', '#000000'],
  },
  {
    'name': 'Zimbabwe',
    'flag': '🇿🇼',
    'code': 'ZW',
    'dialCode': '+263',
    'colors': ['#006A4E', '#FFD700', '#000000', '#FF0000', '#FFFFFF'],
  },
]

console.log(
  pipe(
    Array.map(countries, (info) => info.name.length),
    (array) =>
      Array.isArrayNonEmpty(array) ? Array.max(array, Order.Number) : 0
  )
)

export const dialCodeToCountryInfoHashMap = HashMap.fromIterable(
  countries.map((info) => [Number(info.dialCode), info])
)

export const getCountryInfo = (
  dialCode: number
): Option.Option<CountryInterface> => {
  return Array.findFirst(
    countries,
    (info) => Number(info.dialCode) === dialCode
  )
}
