import {SqlClient} from '@effect/sql'
import {Effect} from 'effect'

export default Effect.flatMap(
  SqlClient.SqlClient,
  (sql) => sql`
    CREATE TABLE databasechangelog (
      id varchar(255) NOT NULL,
      author varchar(255) NOT NULL,
      filename varchar(255) NOT NULL,
      dateexecuted timestamp NOT NULL,
      orderexecuted integer NOT NULL,
      exectype varchar(10) NOT NULL,
      md5sum varchar(35),
      description varchar(255),
      comments varchar(255),
      tag varchar(255),
      liquibase varchar(20),
      contexts varchar(255),
      labels varchar(255),
      deployment_id varchar(10)
    );

    CREATE TABLE databasechangeloglock (
      id integer NOT NULL PRIMARY KEY,
      locked boolean NOT NULL,
      lockgranted timestamp,
      lockedby varchar(255)
    );

    CREATE TABLE offer_public (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk__offer_public__c7d0f6572656bf34 PRIMARY KEY,
      admin_id varchar NOT NULL,
      offer_id varchar(64) NOT NULL,
      created_at date NOT NULL,
      modified_at date NOT NULL,
      offer_type varchar,
      report integer DEFAULT 0 NOT NULL,
      payload_public varchar,
      refreshed_at date NOT NULL,
      country_prefix integer
    );

    CREATE TABLE offer_private (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk__offer_private__c7d0f6572656bf34 PRIMARY KEY,
      user_public_key varchar NOT NULL,
      offer_id bigint NOT NULL CONSTRAINT fk_offer_id REFERENCES offer_public,
      payload_private varchar
    );

    CREATE INDEX b39b5689c5d04cf5b350_ix ON offer_private (user_public_key);

    CREATE INDEX "106ec2a9167f4c6ea801_ix" ON offer_public (offer_id);

    CREATE INDEX c2f312ff936f491d8be3_ui ON offer_public (admin_id);

    CREATE TABLE offer_reported_record (
      id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_offer_reported_record" PRIMARY KEY,
      user_public_key varchar NOT NULL,
      reported_at timestamp NOT NULL
    );

    CREATE INDEX "I_reports_pub_key" ON offer_reported_record (user_public_key);
  `
)
