import {SqlClient} from '@effect/sql'
import {Effect} from 'effect'

export default Effect.flatMap(
  SqlClient.SqlClient,
  (sql) => sql`
    CREATE SEQUENCE IF NOT EXISTS note_change_counter_seq;

    COMMENT ON SEQUENCE note_change_counter_seq IS 'Shared by note_public.update_counter and note_private.update_counter; intentionally not OWNED BY a single column. Dedicated to notes, separate from offer_change_counter_seq.';

    CREATE TABLE note_public (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      admin_id varchar NOT NULL,
      note_id uuid NOT NULL,
      payload_public varchar NOT NULL,
      expires_at timestamp NOT NULL,
      created_at timestamp NOT NULL DEFAULT NOW(),
      report integer DEFAULT 0 NOT NULL,
      update_counter bigint NOT NULL DEFAULT nextval('note_change_counter_seq')
    );

    CREATE UNIQUE INDEX note_public_admin_id_ix ON note_public (admin_id);

    CREATE UNIQUE INDEX note_public_note_id_ix ON note_public (note_id);

    CREATE INDEX note_public_expires_at_ix ON note_public (expires_at);

    CREATE INDEX note_public_update_counter_ix ON note_public (update_counter);

    CREATE TABLE note_private (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_public_key varchar NOT NULL,
      note_id bigint NOT NULL CONSTRAINT fk_note_id REFERENCES note_public ON DELETE CASCADE,
      payload_private varchar NOT NULL,
      repost_id varchar,
      update_counter bigint NOT NULL DEFAULT nextval('note_change_counter_seq')
    );

    CREATE INDEX note_private_note_id_ix ON note_private (note_id);

    CREATE INDEX note_private_repost_id_ix ON note_private (repost_id);

    CREATE INDEX note_private_user_public_key_update_counter_id_ix ON note_private (user_public_key, update_counter, id);

    CREATE TABLE note_reported_record (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_public_key varchar NOT NULL,
      reported_at timestamp NOT NULL
    );

    CREATE INDEX note_reported_record_user_public_key_ix ON note_reported_record (user_public_key);
  `
)
