name: "[Build] feedback-service docker image"
run-name: "Run on commit ${{github.sha}} for environment ${{inputs.env}}"

permissions:
  packages: write
  contents: write
  id-token: write

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to build"
        required: true
        type: choice
        options:
          - prod
          - stage
          - dev
  workflow_call:
    inputs:
      env:
        description: "Environment to build"
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6
        with:
          role-to-assume: arn:aws:iam::570620554963:role/github_actions_ecr_vexl
          role-session-name: GithubActionsCloudInfrastructure
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          cache-from: type=gha,scope=feedback-service
          cache-to: type=gha,mode=max,scope=feedback-service
          tags: |
            ghcr.io/vexl-it/feedback-service:latest
            ghcr.io/vexl-it/feedback-service:${{inputs.env}}-${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/feedback-service:${{inputs.env}}-${{ github.sha }}
          build-args: |
            APP=feedback-service
            SERVICE_DISPLAY_NAME=Feedback service
            SERVICE_VERSION=${{ github.sha }}
            ENVIRONMENT=${{ inputs.env }}
