name: "[Release] build eas production"
run-name: "Run on commit ${{github.sha}}"

on:
  workflow_dispatch:
    inputs:
      altStore:
        description: "Build for AltStore"
        required: false
        type: boolean
        default: false
      testFlight:
        description: "Build for TestFlight"
        required: false
        type: boolean
        default: false
      playStore:
        description: "Build for PlayStore"
        required: false
        type: boolean
        default: false

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: yarn workspaces focus @vexl-next/mobile-app
      - name: Decode Google Service Account key
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        run: |
          mkdir -p apps/mobile/credentials && echo $GOOGLE_SERVICE_ACCOUNT > apps/mobile/credentials/google.json

  altStore:
    name: Build for AltStore
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ inputs.altStore == 'true' || inputs.altStore == true }}
    steps:
      - name: Build on EAS for AltStore
        run: |
          eas build --platform ios --profile productionAltStore --auto-submit --non-interactive --no-wait
        working-directory: apps/mobile

  testFlight:
    name: Build for TestFlight
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ inputs.testFlight == 'true' || inputs.testFlight == true }}
    steps:
      - name: Build on EAS for TestFlight
        run: |
          eas build --platform ios --profile productionTestFlight --auto-submit --non-interactive --no-wait
        working-directory: apps/mobile

  playStore:
    name: Build for PlayStore
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ inputs.playStore == 'true' || inputs.playStore == true }}
    steps:
      - name: Build on EAS for PlayStore
        run: |
          eas build --platform android --profile productionPlayStore --auto-submit --non-interactive --no-wait
        working-directory: apps/mobile
