name: "[Release] Build & submit to store"
run-name: "Build & submit ${{ inputs.platform }} (${{ inputs.environment }}) on ${{ github.sha }}"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to build & submit"
        required: true
        type: choice
        default: staging
        options:
          - staging
          - production
      platform:
        description: "Platform to build & submit"
        required: true
        type: choice
        default: all
        options:
          - all
          - android
          - ios
  workflow_call:
    inputs:
      environment:
        description: "Environment to build & submit"
        required: true
        type: string
      platform:
        description: "Platform to build & submit (all|android|ios)"
        required: false
        type: string
        default: all

jobs:
  build-submit:
    name: Build & submit to store
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24.x
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@eab7a230208c952974db8c3245cfd78402c7b385 # v9
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --filter @vexl-next/mobile-app...
      - name: Decode Google Service Account key
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        run: |
          mkdir -p apps/mobile/credentials && echo "$GOOGLE_SERVICE_ACCOUNT" > apps/mobile/credentials/google.json
      - name: Build on EAS and submit to store
        run: eas build --platform ${{ inputs.platform }} --profile ${{ inputs.environment }} --auto-submit --non-interactive --no-wait
        working-directory: apps/mobile
