jobs:
  release:
    name: "[Release] Build selected targets"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: yarn workspaces focus @vexl-next/mobile-app
      - name: Decode Google Service Account key
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        run: |
          mkdir -p apps/mobile/credentials && echo $GOOGLE_SERVICE_ACCOUNT > apps/mobile/credentials/google.json

      - name: Build for AltStore
        if: ${{ inputs.altStore == 'true' || inputs.altStore == true }}
        run: |
          eas build --platform ios --profile productionAltStore --auto-submit --non-interactive --no-wait
        working-directory: apps/mobile

      - name: Build for TestFlight
        if: ${{ inputs.testFlight == 'true' || inputs.testFlight == true }}
        run: |
          eas build --platform ios --profile productionTestFlight --auto-submit --non-interactive --no-wait
        working-directory: apps/mobile

      - name: Build for PlayStore
        if: ${{ inputs.playStore == 'true' || inputs.playStore == true }}
        run: |
          eas build --platform android --profile productionPlayStore --auto-submit --non-interactive --no-wait
        working-directory: apps/mobile
