name: "[Test] run jest tests (unit and integration)"
run-name: "Run on commit ${{github.sha}}"

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run jest tests on all packages
    timeout-minutes: 15
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 && echo "Pg is ready" && break
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
          pg_isready -h localhost -p 5432 || { echo "PostgreSQL failed to start"; exit 1; }

      - name: Run tests
        env:
          TEST_DB_HOST: "localhost"
        run: yarn turbo:test
