name: "[Test] format, lint and typecheck code"
run-name: "Run on commit ${{github.sha}}"

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Lint code
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Run lint
        run: yarn turbo:check-code
